UNC-Libraries/hy-c

app/actors/hyrax/actors/interpret_visibility_actor.rb, app/views/hyrax/base/_form_permission_embargo.html.erb, app/views/hyrax/base/_form_relationships.html.erb, spec/features/edit_work_spec.rb, spec/features/set_embargo_spec.rb
I added a conditional checking if the current user is an admin in the interpret_visibility_actor file to allow the embargo release date restrictions from admin sets to be ignored.  I also found an error in the logic in the form_relationships file which reset the admin set to the default for the given work type even if an administrator had selected a different admin set.  I fixed that error here because I needed it working in order to test the override abilities.
=> Override admin set policies

config/database.yml
The database connection is a little different on QA, and we need to provide the correct db name and host in each environment.
Also need to add `DATABASE_URL: 'postgresql://localhost:5432'` variable to config/local_env.yml locally and `DATABASE_URL: 'postgresql://hamilton.libint.unc.edu:5432'` on QA.
=> Update production db config in database.yml for qa

app/assets/javascripts/unc_custom.js, app/controllers/application_controller.rb, app/controllers/masters_papers_controller.rb, app/controllers/omniauth_controller.rb, app/presenters/hyrax/homepage_presenter.rb, app/presenters/hyrax/unrestricted_select_type_list_presenter.rb, app/services/hyrax/unrestricted_classification_query.rb, app/views/_controls.html.erb, app/views/_user_util_links.html.erb, app/views/hyrax/homepage/_unc_deposit.html.erb, app/views/hyrax/homepage/_unc_masthead.html.erb, app/views/hyrax/homepage/index.html.erb, app/views/shared/_select_work_type_modal.html.erb, spec/controllers/masters_papers_controller_spec.rb, spec/presenters/hyrax/unrestricted_select_type_list_presenter_spec.rb
* Users forwarded to the page they requested or were on when they are prompted to log in to shibboleth.
* Modals for selecting worktype to deposit display options prior to logging in
* After selecting a worktype, the user will be prompted to log in and then sent to form
* Fixes issue where student papers modal displayed the full set of worktypes after visiting any page other than the front page.
This involved disabling turbolinks for login links, overriding hyrax default post-sign-in page, and passing `origin` parameter to shibboleth.
=> Hyc-228 - Sign-in order and worktype visibility

app/views/hyrax/base/_show_actions.html.erb, config/workflows/default_workflow.json, config/workflows/honors_thesis_deposit_workflow.json, config/workflows/mediated_deposit_workflow.json
* Adds requests to delete items to all workflows
* Adds tombstone option to all workflows for admins
* `Request Deletion` button available for users after edit options are removed by workflow
To deploy the workflow changes, `scl enable rh-ruby24 -- rails hyrax:workflow:load` must be run
=> Hyc-225 - Requests/Tombstones for all workflows

config/workflows/default_workflow.json, config/workflows/honors_thesis_deposit_workflow.json, config/workflows/mediated_deposit_workflow.json
1. Revoke edit status if admin tombstones a record.
2. Prevents direct downloads of "Pending Deletion" records.
https://jira.lib.unc.edu/browse/HYC-239
=> Restrict access for tombstones and tombstone requests.

app/views/hyrax/base/_items.html.erb, app/views/hyrax/file_sets/media_display/_audio.html.erb, app/views/hyrax/file_sets/media_display/_default.html.erb, app/views/hyrax/file_sets/media_display/_image.html.erb, app/views/hyrax/file_sets/media_display/_office_document.html.erb, app/views/hyrax/file_sets/media_display/_pdf.html.erb, app/views/hyrax/file_sets/media_display/_video.html.erb
State doesn't persist onto file pages, and only seems to exist in the context of a workflow. This should show/hide files correctly. The only exception is the file owner can still see thumbnails with a direct link to the files page, which is maybe okay.
=> Show file page thumbnails for public works that haven't been withdrawn

.travis.yml
Out tests don't seem to run when in the script block of the travis config. Moving them back to the before_script block causes them to run.
=> Tests don't seem to run

app/models/solr_document.rb, app/presenters/hyrax/honors_thesis_presenter.rb
Small addition to the normalizing label names pull request. This is another place where 'url' field needs to be removed
=> Remove url field from solr doc. Not used in any form

app/controllers/hyrax/users_controller.rb
https://jira.lib.unc.edu/browse/HYC-350 
Allow authenticated users to see user list. Needed for depositors to search for users to share with.
=> Allow users to search for users to share with

app/models/article.rb, app/models/artwork.rb, app/models/data_set.rb, app/models/dissertation.rb, app/models/general.rb, app/models/honors_thesis.rb, app/models/journal.rb, app/models/masters_paper.rb, app/models/multimed.rb, app/models/scholarly_work.rb, config/locales/hyrax.en.yml
This will remove deprecation warnings from the logs like: 
```DEPRECATION WARNING: human_readable_type= is deprecated and will be removed from a future release (human_readable_type is deprecated. Set the i18n key for activefedora.models.#{model_name.i18n_key} instead. This will be removed in Hyrax 3). (called from <class:Artwork> at /hyrax/app/models/artwork.rb:11)```
=> Remove deprecated human_readable_type method

app/presenters/hyrax/workflow_presenter.rb
Hide panel from non-admins if the workflow action is to withdraw/delete the work.
https://jira.lib.unc.edu/browse/HYC-447
=> Hide panel from non-admins if the workflow action is withdraw

lib/tasks/migrate/migrate.rake, lib/tasks/migrate/services/id_mapper.rb, lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/progress_tracker.rb, spec/tasks/migrate_rake_spec.rb
Resolves: https://jira.lib.unc.edu/browse/HYC-487
* Changed third parameter for the migrate script to be an output folder instead of the mappings file (which is now added to the output folder, along with other files)
* Track the progress of objects successfully migrated. If the script is resumed, these objects will be skipped.
* Track the progress of parents which have their children attached. If the script is resumed, these objects will be skipped.
* Store the parent to child mapping in a CSV file, reload at the end when 
* Fix the new id recorded for honors thesis object
* Record the amount of time taken to update the children per object
=> HYC-470 - Migration recoverability

lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/metadata_parser.rb
* Added setting to allow children works to be added to a separate admin set from their parents
* Minor refactoring of how admin sets get looked up
https://jira.lib.unc.edu/browse/HYC-528
=> HYC-528 - Migrate child works to own admin set

app/assets/javascripts/unc/unc_visibility_component.es6
Make sure "Public" message opens when "Public" visibility option is auto-selected.
https://jira.lib.unc.edu/browse/HYC-646
=> Make sure "Public" message opens when "Public" visibility option checked

lib/tasks/migrate/migrate.rake, lib/tasks/migrate/services/child_work_parser.rb, lib/tasks/migrate/services/ingest_service.rb
the rake task tries to redo previous parent-child relationships and fails when there is a work type mismatch
=> Store parent-child mappings in separate files for each collection

config/authorities/proquest_departments.yml, lib/tasks/proquest_ingest.rake, spec/features/create_artwork_spec.rb
* Updates department and degree mappings for proquest records
* Some departments were not in existing authority
* One department was mapped to the wrong key
* It looks like the proquest abbreviation for the doctor of education degree changed from E.D.D. to D.E., so we now have both in the mapping
* Will store non-mapping departments in fedora in the future for easier remediation
* Adds log statements to help identify new records and log zip file errors
* Fixes artwork feature test
=> Proquest ingest update

.travis.yml, Gemfile, Gemfile.lock
* https://jira.lib.unc.edu/browse/HYC-970
* updated travis-ci config file
* upgraded webmock gem so tests would run with ruby26
=> hyc-970 ruby 26 upgrade

app/actors/hyrax/actors/file_actor.rb, app/jobs/register_to_longleaf_job.rb, spec/jobs/register_to_longleaf_job_spec.rb
* https://jira.lib.unc.edu/browse/HYC-1061
* passing the Hyrda::PCDM::File object to the job was causing errors
=> Pass checksum to longleaf registration job instead of Hydra::PCDM::File object

app/jobs/assign_permissions_to_work_job.rb, config/workflows/honors_thesis_deposit_workflow.json, spec/features/create_work_in_honors_thesis_workflow_spec.rb
https://jira.lib.unc.edu/browse/HYC-1111
Use honors reviewer notification for post-permission assignment notification. Remove direct notification call from workflow
=> HYC-1111 - Fix honors reviewer notification

app/forms/hyrax/honors_thesis_form.rb, app/views/records/edit_fields/_person.html.erb, spec/forms/hyrax/honors_thesis_form_spec.rb
Require affiliation for honors thesis creator in partial, since it's really part of creator sub form. It's the only required affiliation. It gives a log warning if set in the honors thesis form.
https://jira.lib.unc.edu/browse/HYC-1126
=> Require affiliation for honors thesis creator in partial

app/services/hyrax/workflow/assign_reviewer_by_affiliation.rb
Replace dashes in dept names with underscore for email notifications, as PostGres doesn't seem to do well with dashes.
https://jira.lib.unc.edu/browse/HYC-1150
=> Replace dashes in dept names with underscore for email notifications

app/jobs/attach_files_to_work_job.rb, spec/fixtures/files/odd_chars_+.txt, spec/lib/hyc/virus_scanner_spec.rb
* Make sure file paths are decoded
* Add test in virus_scanner_spec.rb, as this is where encoded paths fail
https://jira.lib.unc.edu/browse/HYC-1181
=> Make sure file paths are decoded

app/actors/hyrax/actors/base_actor.rb
File sets don't have admin sets. So updating them independently of their work should skip apply_work_specific_permissions update.
https://jira.lib.unc.edu/browse/HYC-1203
=> Skip applying work specific permissions for filesets

config/environments/development.rb
Added a "raise" to a footer to verify the change
=> Allow Vagrant IP address to display web console in development mode

spec/fixtures/tmp/.keep, spec/jobs/create_derivatives_job_spec.rb
- The test currently assumes that the data and temp storage are in the same place. Add TODO to update the test to treat these directories separately
- In the context of the test, the virus checker method is not finding the file that's passed in, even though it is present. This does not seem to be an issue in production, and is not the focus of these tests, so mock out the virus check method
=> Get test for CreateDerivativesJob passing on VM and in CI

.github/workflows/build.yml, spec/controllers/hyrax/work_type_controller_spec.rb, spec/features/edit_work_spec.rb, spec/presenters/hyrax/stats_usage_presenter_spec.rb, spec/services/tasks/doi_create_service_spec.rb, spec/services/tasks/onescience_ingest_service_spec.rb, spec/tasks/migrate_rake_spec.rb
- Re-apply changes to clean up history
- For some tests, clean out Fedora, Solr, and database prior to test, to ensure we can create a new unique object when we expect to.
- Create object in test, rather that prior to all tests. 
- Ensure consistent environment for tests
- Delete temp files after test completes
- Mark test that is flaky on VM (both on main and this branch) as pending
- Have created ticket to deprecate or refactor this code - https://jira.lib.unc.edu/browse/HYC-1273
Connected to https://jira.lib.unc.edu/browse/HYC-1270
=> Get tests passing consistently on VM

.github/workflows/build.yml
- Latest Rubygems update breaks CI, use specific version to fix CI, can investigate when / if we want to upgrade in future.
=> Update to Rubygems version on server

config/initializers/git_sha.rb
On cdr-test without this fix after deploying v1.0.0
With change -
=> If we are not on a branch, and are on a tag, use tag name

config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
Use the same log formatter in test and development environments to ensure log tagging is working correctly, and in order to create new tagged logs in future.
Test - before
```
ActiveFedora: loading fedora config from /hyrax/config/fedora.yml
ActiveFedora: loading solr config from /hyrax/config/solr.yml
[1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
[1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
[1m[35m (0.1ms)[0m  [1m[31mROLLBACK[0m
[1m[35m (0.1ms)[0m  [1m[35mBEGIN[0m
[1m[35m (0.2ms)[0m  [1m[31mROLLBACK[0m
```
Test - after
```
2021-12-13 16:39:59 +0000 - INFO: ActiveFedora: loading fedora config from /hyrax/config/fedora.yml
2021-12-13 16:39:59 +0000 - INFO: ActiveFedora: loading solr config from /hyrax/config/solr.yml
2021-12-13 16:39:59 +0000 - DEBUG:   [1m[35m (0.1ms)[0m …
```
=> Use same log formatting for all environments

config/application.rb
When attempting to deploy to cdr-test, the logging code was not picking up the environment variable, so it was trying to persist the logs to a place it didn't have write permission, bringing down the whole service.
By creating the logger after the environment variables are loaded fixes this problem.
=> Move log formatter to after environment variables have been loaded

app/lib/qa/authorities/local/file_based_authority.rb, spec/lib/qa/authorities/local/file_based_authority_spec.rb, spec/services/cdr_license_service_spec.rb
Connected to https://jira.lib.unc.edu/browse/HYC-1319
Connected to https://jira.lib.unc.edu/browse/HYC-1280
Sage provides the URIs for licenses with "https", which we only realized when I tried to find the label for them. 
I talked to Anna and Rebekah about being agnostic about mapping URIs to the same authority record whether they use "http" and "https" at the beginning, and they were fine with that. 
We will still only store / return records with "http" as the id, but "#find" will return the record for ids starting with either http or https.
This PR also adds a test for one of our overrides - Qa::Authorities::Local::FileBasedAuthority - this override does not appear to have been tested specifically previously.
=> Allow authority to find http or https

.github/workflows/build.yml, .rubocop.yml, app/actors/hyrax/actors/file_actor.rb, app/lib/hyc/virus_scanner.rb, spec/actors/hyrax/actors/file_actor_spec.rb, spec/lib/hyc/virus_scanner_spec.rb, spec/services/tasks/onescience_ingest_service_spec.rb, spec/services/tasks/proquest_ingest_service_spec.rb
- Raise and then rescue error when can't save file_set
- Raise error when we get a ClamAV error
- Remove fits from CI, wasn't working anyway, mocking in tests 
- Allow to rescue with `error` rather than `e`
=> HYC-1345: Increase error handling for background jobs

.github/workflows/build.yml
- Upgrading to bundler 2.2.18 did not result in any changes to the Gemfile.lock 
- Once the upgrade to bundler has been done on all the deployed servers, we can update the `BUNDLED WITH` in the Gemfile.lock (run `bundler update --bundler`). Bundler doesn't usually complain if you bundle with a newer version than is in the lockfile, but does if it's an older version.
=> HYC-1396: Update tests for security upgrades

app/jobs/list_unmappable_affiliations_job.rb, app/services/hyc_crawler_service.rb, spec/jobs/list_unmappable_affiliations_spec.rb, spec/services/hyc_crawler_service_spec.rb
Typo also needs to be fixed in hyrax-vagrant code - https://gitlab.lib.unc.edu/cdr/vagrant-rails/-/merge_requests/126
=> Fix typo and use delimiter for packed CSV field

.codeclimate.json
- This is basically the default configuration, with more exclusions, but makes it easier to run checks locally, and set the stage for further modifications
=> HYC-1401: Add config for codeclimate to repo

app/jobs/remediate_affiliations_job.rb, app/services/affiliation_remediation_service.rb, app/services/departments_service.rb, lib/tasks/list_affiliations.rake, spec/fixtures/files/short_unmappable_affiliations.csv, spec/fixtures/files/umappable-affiliations-mapped-final.csv, spec/jobs/remediate_affiliations_job_spec.rb, spec/services/affiliation_remediation_service_spec.rb
Each environment should have a list of affiliations. The mapping list is not unique to each environment (we only did it for production), but I think testing the job on the other environments will be enough to see if it's working.
=> HYC-1390: Create job and service to remediate affiliations

app/services/proquest_department_mappings_service.rb, app/services/tasks/proquest_ingest_service.rb, spec/services/proquest_department_mappings_service_spec.rb, spec/services/tasks/proquest_ingest_service_spec.rb
- Affiliations that can't be mapped to a standardized department ID will be recorded as other_affiliation
- The fact that it could not be mapped will be included in the ProQuest logs, nested within the logs for a specific object, so it will be clear which object should be re-visited.
=> HYC-1400: ProQuest affils that are not standard

.github/workflows/build.yml, app/services/affiliation_remediation_service.rb, app/services/departments_service.rb, app/services/hyc_crawler_service.rb, app/services/tasks/doi_create_service.rb, config/authorities/departments.yml, lib/active_fedora/rdf/indexing_service.rb, lib/tasks/migrate/services/metadata_parser.rb, spec/fixtures/authorities/departments.yml, spec/indexers/hyc_indexer_spec.rb, spec/services/affiliation_remediation_service_spec.rb, spec/services/departments_service_spec.rb
Note: I updated the departments controlled vocabulary on the console, assigning each `short_label` to the current id. 
The idea is to allow the short_label and id to drift from each other, *without* the ids themselves needing to drift.
```ruby
vocab = YAML.load_file('config/authorities/departments.yml')
vocab['terms'].map { |term| term['short_label'] = term['id'] }
File.open('config/authorities/departments.yml', "w") { |file| file.write(vocab.to_yaml(line_width: -1)) }
```
=> HYC-1398: Add short label to department service

config/initializers/hyrax.rb
Relates to https://jira.lib.unc.edu/browse/HYC-1441
When uploading a large video file was timing out during derivative generation, which is not the cause of the original issue, but impacts the same object when the mp4 file is uploaded instead of the m4a file.
=> HYC-1441 - Increase timeout for video derivative generation

app/search_builders/range_limit_catalog_search_builder.rb
https://jira.lib.unc.edu/browse/HYC-1404
Fix bug that was adding an empty search to advanced searches whenever all_fields was unpopulated, which was causing searches for specific fields to match everything, and causing filters by facets to return no results when no search terms were provided
=> HYC-1404 - Fix advanced search returning everything or nothing

app/services/tasks/solr_migration_service.rb, spec/services/tasks/solr_migration_service_spec.rb
Part of https://jira.lib.unc.edu/browse/HYC-1262
Handle uncaught errors so they show up in the logs, and handle object not found
=> HYC-1262 - Additional error handling for reindex

docker-compose.yml
* Switch mount-code to using two-way-resolved sync mode, to prevent conflicts from stopping syncs of updated files in git from reaching the container
=> Change sync mode for mount-code

app/jobs/attach_files_to_work_job.rb, app/overrides/jobs/attach_files_to_work_job_override.rb, spec/jobs/attach_files_to_work_job_spec.rb
https://jira.lib.unc.edu/browse/HYC-1490
* Add tests for overrides
* Change approach to override, removing non-overridden code, and wrapping the original method
* Change infected file behavior, so it now will only delete the pattern dir containing the file if its empty. Also, catch any errors that occur during deletion so email always gets sent.
=> HYC-1490 - Test coverage/refactor for attach_files_to_work_job overrides

app/services/tasks/solr_migration_service.rb, spec/services/tasks/solr_migration_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-1558
* Update counts in solrmigration spec to take into account new embargo and lease objects
* Adjust indexing order to place adminsets before works/filesets, without doing so tests were flapping with regards to the admin_set_tesim field
* Some rubocop fixes
=> HYC-1558 - Update SolrMigartionService to work with hyrax 3

spec/features/create_masters_paper_spec.rb
* Update geonames response based on what new version of Questioning Authority is expecting. Also determined that caching mechanism prevents the URLs from being requested again across test runs, so have to be careful with that.
=> HYC-1556 - Update geonames response

app/overrides/presenters/hyrax/google_scholar_presenter_override.rb, app/overrides/presenters/hyrax/work_show_presenter_override.rb, app/presenters/hyrax/article_presenter.rb, app/presenters/hyrax/data_set_presenter.rb, app/presenters/hyrax/dissertation_presenter.rb, app/presenters/hyrax/general_presenter.rb, app/presenters/hyrax/honors_thesis_presenter.rb, app/presenters/hyrax/journal_presenter.rb, app/presenters/hyrax/masters_paper_presenter.rb, app/presenters/hyrax/scholarly_work_presenter.rb, app/views/shared/_citations.html.erb, spec/presenters/hyrax/article_presenter_spec.rb, spec/presenters/hyrax/artwork_presenter_spec.rb, spec/presenters/hyrax/data_set_presenter_spec.rb, spec/presenters/hyrax/dissertation_presenter_spec.rb, spec/presenters/hyrax/general_presenter_spec.rb, spec/presenters/hyrax/honors_thesis_presenter_spec.rb, spec/presenters/hyrax/journal_presenter_spec.rb, spec/presenters/hyrax/masters_paper_presenter_spec.rb, spec/presenters/hyrax/multimed_presenter_spec.rb, spec/presenters/hyrax/scholarly_work_presenter_spec.rb, spec/views/shared/_citations.html.erb_spec.rb
https://jira.lib.unc.edu/browse/BXC-3808
* Update google scholar metadata population to use GoogleScholarPresenter, which is the current approach in hyrax
* Add `scholarly?` method for work presenters, which is referenced by `GoogleScholarPresenter.scholarly?`. 
* Presenters default to scholarly=false, but all work types except Artwork and Multimedia override it to true
=> HYC-1565 - Update Google Scholar for hyrax 3

config/role_map.yml
To resolve the following error on forms pages:
```
ActionView::Template::Error (No roles were found for the p
roduction environment in /net/deploy/ir/test/releases/20221129124310/config/role_map.yml)
```
=> Add a role mapping for production to prevent failure on forms pages

.github/workflows/build.yml, app/controllers/catalog_controller.rb, app/overrides/services/hyrax/solr_query_service_override.rb, config/analytics.yml
Part of https://jira.lib.unc.edu/browse/HYC-1583
* Fix for analytics config that was causing the dashboard to fail to load
* Switch solr queries to using POST since the review submissions page was producing solr URLs that were too long (this change is in the catalog_controller template in hyrax)
* Switch to using different fedora container for gh actions, since previous one stopped working. Now it is consistent with the dev vm
=> HYC-1583 - Fix analytics and solr config

app/overrides/factories/bulkrax/object_factory_override.rb, spec/models/bulkrax/object_factory_spec.rb
https://jira.lib.unc.edu/browse/HYC-1603
* Register ids of people objects which are not listed in a CSV import as needing to be destroyed (will not destroy them if there are no fields related to a particular person type in the import)
=> HYC-1603 - Cleanup people objects in bulkrax

Gemfile, Gemfile.lock, app/models/ability.rb, app/overrides/models/concerns/bulkrax/import_behavior_override.rb, app/overrides/parsers/bulkrax/csv_parser_override.rb, app/views/hyrax/dashboard/sidebar/_activity.html.erb, config/initializers/bulkrax.rb
https://jira.lib.unc.edu/browse/HYC-1605
* Using recent commit of bulkrax to pull in upstream fixes, removed overlapping local overrides
* Enables new config option to cleanup empty fields during import
* Adds in two new ability methods which are required by upstream changes
* Remove the old bulkrax links from the dashboard menu in favor of the ones now being added by bulkrax, and restrict bulkrax permissions to admins (to match previous permissions)
=> HYC-1605 - Update from bulkrax upstream

app/models/ability.rb
https://jira.lib.unc.edu/browse/HYC-1613
* When no depositor set for a work, user_is_depositor? will return false instead of an error so that the dashboard work page still functions
=> HYC-1613 - Error showing work with no depositor in dashboard

app/jobs/deregister_longleaf_job.rb, app/models/concerns/hyc/file_set_behavior.rb, spec/jobs/deregister_longleaf_job_spec.rb, spec/models/file_set_spec.rb
https://jira.lib.unc.edu/browse/HYC-1617
Pass checksum to deregister job (used to compute the fedora path) instead of the fileset, since the fileset will likely not exist anymore by the time the job executes
=> HYC-1617 - DeregisterLongleafJob - ActiveJob::DeserializationError

config/initializers/bulkrax.rb
https://jira.lib.unc.edu/browse/HYC-1622
* Add split expressions to each field, since the default value does not seem to be used.
* Enable splitting on funder
=> HYC-1622 - Bulkrax, don't split on :'s

app/overrides/services/hyrax/analytics/google/events_daily_override.rb, app/overrides/services/hyrax/analytics/google/events_override.rb
https://jira.lib.unc.edu/browse/HYC-1630
* Present DownloadIR stat for work downloads instead of file-set-in-work-download, since DownloadIR records all downloads (not just via the UI) and it includes stats from hyrax 2 and 3
=> HYC-1630 - Use DownloadIR in place of file-set-in-work-download for display

app/views/hyrax/file_sets/media_display/_audio.html.erb, app/views/hyrax/file_sets/media_display/_default.html.erb, app/views/hyrax/file_sets/media_display/_image.html.erb, app/views/hyrax/file_sets/media_display/_office_document.html.erb, app/views/hyrax/file_sets/media_display/_pdf.html.erb, app/views/hyrax/file_sets/media_display/_video.html.erb
https://jira.lib.unc.edu/browse/HYC-1628
* Include all the same data in the various download links as are in the fileset list download link
=> HYC-1628 - Fix missing work-id on file-set-in-work-download events

app/views/hyrax/stats/_downloads.html.erb, app/views/hyrax/stats/_pageviews.html.erb, config/locales/hyrax.en.yml
https://jira.lib.unc.edu/browse/HYC-1632
* Change the period of stats displayed for works from 30 to 365 days
* Update headers of graphs to indicate they display a year
=> HYC-1632 - adjust and clarify time periods of stats

app/models/search_builder.rb, app/overrides/search_builders/hyrax/catalog_search_builder_override.rb
https://jira.lib.unc.edu/browse/HYC-1637
* Only add advanced search functionality to the catalog_search_builder rather than to all search builders, which was interfering with adding subcollections
=> HYC-1637 - Fix error when adding subcollections

app/overrides/controllers/hyrax/my/works_controller_override.rb
https://jira.lib.unc.edu/browse/HYC-1637
* Clear search parameters in CollectionService when populating list of possible collections to add works to, otherwise it will often result in it stating no collections are available
=> HYC-1637 - Fix inability to add to collections when a search term is present

app/overrides/controllers/hydra/controller/download_behavior_override.rb, spec/controllers/hyrax/downloads_controller_spec.rb, spec/fixtures/files/no_extension
https://jira.lib.unc.edu/browse/HYC-1646
* Adjust download filename logic to add extensions when they don't match the vocab, and to return the original filename if it already has the right extension.
=> HYC-1646 - Use vocab extension from mimetype when no original filename extension

app/services/hyrax/workflow/assign_reviewer_by_affiliation.rb
https://jira.lib.unc.edu/browse/HYC-1676
* Escape all non-alphanumeric characters in department names when generating reviewer groups, and reduce multiple _'s in a row down to one.
=> HYC-1676 - Fix issue assigning reviewers in depts containing /

app/services/languages_service.rb, app/services/tasks/doi_create_service.rb, config/authorities/languages.yml, spec/fixtures/authorities/languages.yml, spec/services/tasks/doi_create_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-1687
* Converts languages to iso639-1, which is the required format for languages in datacite
* Language vocab now has iso639-1 values when one exists.
* Removes contributors from datacite request as they are no longer supported by its API
* Excludes items without publication dates from receiving a DOI (it is a required field)
* Items with invalid publication dates will fall back to the date the work was created (dates must be YYYY)
* Dates that are in decade/century format will converted back an actual date (18xx becomes 1800)
* resourceTypeGeneral now falls back to 'Text' if we are unable to determine a value (it is a required field). resourceType falls back to the resourceTypeGeneral if none is available (also a required field)
=> HYC-1687 - DOI script fixes

app/views/hyrax/my/_work_action_menu.html.erb
https://jira.lib.unc.edu/browse/HYC-1675
This PR adjusts the override hy-c has for the work action menu. It moves the edit permission check to just around the edit option, and adds a new permission check just for deletion around the deletion option.
=> HYC-1675 add delete permission check

app/services/tasks/proquest_ingest_service.rb, app/services/tasks/sage_ingest_service.rb
https://jira.lib.unc.edu/browse/HYC-1374
* Add deletion of ingest package to sage ingest service.
*  Proquest cleanup will now happen depending on an environment variable being set rather than which environment it is
=> HYC-1374 - Cleanup sage ingest packages

app/services/tasks/doi_create_service.rb, spec/services/tasks/doi_create_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-1705
* Handle extraction of publication year when date_issued is an array, which gets returned as a ActiveTriples::Relation. This was causing the year to get set to 0000 or 0x00
=> HYC-1705 - DOI creation handle date_issued arrays

app/overrides/services/hyrax/workflow/workflow_action_service_override.rb, app/services/hyrax/workflow/assign_reviewer_by_affiliation.rb, spec/services/hyrax/workflow/workflow_action_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-1718
* Adds retry for sipity additional actions when a ModelMismatch occurs, since they appears to be transient while permissions of children are being modified in Fedora
* Add back in fedora permissions update.
* Remove weird stray -
=> HYC-1718 - Honors thesis approval permissions bug

Gemfile, Gemfile.lock, app/models/solr_document.rb, spec/rails_helper.rb, spec/spec_helper.rb
Part of https://unclibrary.atlassian.net/browse/HYC-1731
* Removes from solr document that we already removed from all the models.
* Update webdrivers and list of expected download paths for chromium so unrelated feature tests will pass again.
=> HYC-1731 - Remove access and use fields from solr document

config/local_env_sample.yml, docker-compose.yml
Resolves https://unclibrary.atlassian.net/browse/HYC-1754
* Store fcrepo-data volume at one directory up, otherwise all the other fcrepo-data directories will get lost sometimes (maybe after editing docker-compose? I'm not sure of the exact trigger, but anything outside of a declared volume is basically temp storage)
* This resolves issues with the forms not loading, since that was caused by the default admin set getting deleted due to fcrepo-data disappearing
=> HYC-1754 - Preserve fcrepo data (hyrax 4)

app/assets/javascripts/hyrax/save_work/required_fields.es6, app/assets/javascripts/person_objects.js, app/assets/javascripts/unc/unc_custom.js, app/assets/javascripts/unc/unc_save_work_control.es6, app/views/hyrax/base/_form_progress.html.erb, app/views/hyrax/base/_form_relationships.html.erb, app/views/hyrax/base/_guts4form.html.erb, app/views/hyrax/collections/_collection_description.erb, app/views/records/edit_fields/_language_label.html.erb, app/views/records/edit_fields/_license_label.html.erb, app/views/records/edit_fields/_person.html.erb, app/views/records/edit_fields/_rights_statement_label.html.erb
https://unclibrary.atlassian.net/browse/HYC-1765
* Fix the duplicate people entries in the deposit forms by switching from `hidden` classes to `d-none`, which is part of the upgrade from bootstrap 3 to 4, so made this change everywhere
* Fixed the file upload form showing up on all the editor tabs, not just the metadata one.
=> HYC-1765 - Duplicate people entries, bootstrap, file upload form (hyrax-4)

Gemfile, Gemfile.lock, spec/rails_helper.rb
* Switched to using data_cleaner, since the previous method was failing to create the hyrax_test database most of the time. The ActiveRecord method used in hyrax seemed to fail to find some bulkrax tables, even though they were getting created.
=> Ensure test base created in hyrax 4 docker

app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/base/_form_progress.html.erb
- https://unclibrary.atlassian.net/browse/HYC-1770
- https://unclibrary.atlassian.net/browse/HYC-1772
=> Style updates for agreement spacing and facet color contrast

app/assets/javascripts/unc/unc_custom.js, app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/collections/_collection_description.erb, app/views/hyrax/collections/_show_descriptions.html.erb, app/views/hyrax/collections/_subcollection_list.html.erb, app/views/hyrax/collections/show.html.erb
https://unclibrary.atlassian.net/browse/HYC-1787
* Fixes for the dashboard and public collection views
* "Show more" button working
* Update styles to work in bootstrap 4
* Prevent Refresh button from overlapping the work table
* Spacing fixes between thumbnails and titles
* Adds in more hyc-override tags to clarify where changes are, and in some cases mark files that were not previously
* Merge in a few upstream changes to collection pages
=> HYC-1787 - Display issues on collection pages (hyrax-4)

Gemfile, Gemfile.lock
https://unclibrary.atlassian.net/browse/HYC-1790
* Use a local branch of blacklight 7.34.0 which has a fix for the advanced search start over button (see the PR here https://github.com/projectblacklight/blacklight/pull/3092 for details)
* Incidentally, this updates blacklight from 7.33.1 to 7.34.0
=> HYC-1790 - Advanced search "start over" button (hyrax-4)

Gemfile.lock
https://unclibrary.atlassian.net/browse/HYC-1799
Addresses the issue of the dashboard collections and works pages' tabs not doing anything when clicked by updating bulkrax to include a fix for a runaway event binding. The change is here: https://github.com/samvera-labs/bulkrax/pull/874
=> HYC-1799 - Fix dashboard collections/works tabs (hyrax-4)

app/controllers/application_controller.rb, app/controllers/errors_controller.rb
https://unclibrary.atlassian.net/browse/HYC-1810
* Fixes errors when invalid info.json URLs are requested, which were throwing a 500 error due to two issues:  
* It was trying to find a json version of the base error pages, but we only had html (now it explicitly will use the html format error page instead of trying to find a non-existent json version)
* for riiif errors, it was trying to use `render_json_response` from `Hyrax::Controller` which is included in our `ApplicationController`, but for some reason the helper method is not available (maybe because its private? not sure)
=> HYC-1810 - MissingTemplate error for info.json requests

app/services/tasks/group_permission_remediation_service.rb, lib/tasks/remediate_group_permissions.rake, spec/services/tasks/group_permission_remediation_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1781
* Script for remediating missing group assignments on sage/proquest works
* 
it grabs the permissions defined on the admin set associated with the works and ensures the managers and viewers assigned to it are assigned to the listed works and their files
=> HYC-1781 - Remediate Sage/proquest permissions

app/controllers/catalog_controller.rb
https://unclibrary.atlassian.net/browse/HYC-1812
* Comment out CatalogController lines which were setting up bookmark behaviors, since we have disabled the routes for it. Removing these lines resolves `undefined method `bookmark_path'` errors directly, and seem to indirectly resolve the original `guest_uid_authentication_key` error. See the ticket for more details.
=> HYC-1812 - Collection page masonry view errors

app/overrides/presenters/hyrax/file_set_presenter_override.rb
https://unclibrary.atlassian.net/browse/HYC-1814
* Set a rows param on file_set query to find parent work so that it won't generate warnings every time
=> HYC-1814 - Resolve rows not set warning from fileset pages

app/overrides/actors/hyrax/actors/base_actor_override.rb, spec/actors/hyrax/actors/base_actor_spec.rb, spec/actors/hyrax/actors/honors_thesis_actor_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1818
* When setting permissions for users via the Share With feature on the work edit page, it was storing agents in Fedora as `http://projecthydra.org/ns/auth/person#user@example.com` rather than `http://projecthydra.org/ns/auth/person#user`. This is the default behavior in fedora, but not what we are doing everywhere else in the code base, so permissions granted this way were having no affect. So this PR converts email usernames into UIDs when updating the permissions on a work, which resolves the issue
* Removes some additional permission setting overrides from the BaseActor class which do not seem to be needed anymore (I verified that permissions were still getting set via the honors thesis workflow, which appears to have been what the …
=> HYC-1818 - Fix share with user error

app/overrides/lib/qa/authorities/geonames_override.rb, spec/lib/qa/authorities/geonames_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1597
made adjustments for entities returned within location autocomplete
=> HYC-1597 - Eliminating redundant whitespace and preventing duplicate display of countries in Locations autocomplete

app/services/tasks/doi_create_service.rb, spec/services/tasks/doi_create_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1843
- Modified parse_people function in DOI creation service to include UNC ROR metadata
- Updating tests for creation service to check for the ROR information instead of department terms
=> HYC-1843 - UNC-CH ROR metadata inclusion for new DOIs

app/controllers/application_controller.rb, config/initializers/routing_error_logger_defatalizer.rb, spec/controllers/application_controller_spec.rb, spec/features/edit_sage_ingested_works_spec.rb, spec/rails_helper.rb
https://unclibrary.atlassian.net/browse/HYC-1861
* Reduces logging of a number of errors from FATAL to WARN without a full stack trace
* Directs additional errors to appropriate error pages
* Ensures 404 errors use the correct layout, otherwise some errors (such as Ldp::Gone on an edit link) will fail since they try to use the dashboard layout, which throws an error if the user isn't logged in.
* Adds additional chromedriver url to list of real URLs allowed to be accessed during tests, since it keeps moving around and causing tests to fail
* Gets `edit_sage_ingested_works_spec.rb` to pass locally again, which was failing due to javascript not executing. This came to my attention because the test failed in ghactions due to the chromedriver issue. Refactors it to only ingest one work at a …
=> HYC-1861 - Reduce logging of common errors

Gemfile, Gemfile.lock, config/environments/production.rb, config/initializers/riiif.rb
https://unclibrary.atlassian.net/browse/HYC-1862
* Updates RIIIF to most recent version and syncs initializer up hyrax 4 version of the file (with our local modification retained)
* Sets a rails cache_store for production environments, so that caching will go to a path more consistent with the rest of the application
=> HYC-1862 - Update RIIIF and set cache_store

app/overrides/blacklight_oai_provider/resumption_token_override.rb, spec/requests/oai_pmh_endpoint_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1890
Override ResumptionToken in order to handle error when a date is provided, rather than a datetime. Also handle until field. Add test
=> HYC-1890 - Fix oai undefined method utc error

app/controllers/application_controller.rb, config/initializers/routing_error_logger_defatalizer.rb
https://unclibrary.atlassian.net/browse/HYC-1894
* Handle null character in file parameter and in other parts of the requested URL, which addressed "ArgumentError (path name contains null byte)" errors
=> HYC-1894 - Handle null character in download URLs

app/controllers/concerns/hyrax/controller.rb, spec/controllers/application_controller_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1895
* Change the locale param too when an invalid value is provided, so that other parts of the code base that directly access it rather than `I18n.locale` won't receive an invalid locale, such as render_notifications
=> HYC-1895 - Prevent error when logged in with invalid locale

app/middleware/decode_query_string.rb, config/application.rb, spec/middleware/decode_query_string_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1896
Add middleware which decodes equal signs in query strings prior to parameter parsing, to prevent failures when the equal sign separator between the param name and value is encoded
For example, prior to this PR this request fails:
`/catalog?f%5Bkeyword_sim%5D%5B%5D%3DPharmacogenetics&locale=en`
This PR results the query string becoming:
`/catalog?f%5Bkeyword_sim%5D%5B%5D=Pharmacogenetics&locale=en`
So that param parsing will correctly be able to parse out the keyword_sim = Pharmacogenetics search
=> HYC-1896 - Decode equal signs in query string before parsing params

app/controllers/concerns/hyc/download_analytics_behavior.rb, app/models/hyc_download_stat.rb, db/migrate/20240714234200_create_hyc_download_stats.rb, db/schema.rb, spec/controllers/hyrax/downloads_controller_spec.rb, spec/factories/hyc_download_stats.rb, spec/models/hyc_download_stat_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1934
* Add model and migration for HycDownloadStat table
* Modify download analytics tracking behavior so that downloading a file prompts an entry in the table, either adding a new record or updating an existing one.
=> HYC-1934 - Send download events to database

app/overrides/lib/rdf/model/uri_override.rb
https://unclibrary.atlassian.net/browse/HYC-1941
Override RDF::URI in order to wrap the entire freeze method in mutex to try to prevent concurrent attempts to freeze the same URI
=> HYC-1941 - Expand mutex when freezing RDF::URIs

app/services/tasks/set_depositor_service.rb, lib/tasks/set_depositor.rake, spec/services/tasks/set_depositor_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1956
This is just the script for remediating depositors, it does not address the ingest scripts
=> HYC-1956 - script for updating depositors

app/services/tasks/dimensions_ingest_service.rb, app/services/tasks/dimensions_query_service.rb, app/services/tasks/dimensions_reporting_service.rb, app/services/tasks/ingest_helper.rb, app/views/dimensions_report_mailer/dimensions_report_email.erb, lib/tasks/dimensions_ingest.rake, spec/mailers/dimensions_report_mailer_spec.rb, spec/mailers/previews/dimensions_report_mailer_preview.rb, spec/services/tasks/dimensions_ingest_service_spec.rb, spec/services/tasks/dimensions_query_service_spec.rb, spec/services/tasks/dimensions_reporting_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1950
* URL encoding for Dimensions PDF linkouts
* Retrieval of PDF using the Wiley TDM API for specific publications and error handling for potential rate limits
* Dimensions PDF linkouts included in reports
=> HYC-1950 - Dimensions Ingest Failed Downloads QA

app/services/tasks/dimensions_ingest_service.rb, app/services/tasks/dimensions_query_service.rb, spec/fixtures/files/dimensions_ingest_test_fixture.json, spec/services/tasks/dimensions_ingest_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1953
* Specify more variants of UNC in query string, slight tweak to mapping to prioritize UNC affiliations
=> HYC-1951 - Refine Dimensions Query

app/controllers/concerns/hyc/download_analytics_behavior.rb, app/helpers/work_utils_helper.rb, app/services/tasks/download_stats_migration_service.rb, lib/tasks/migrate_download_stats.rake, spec/controllers/hyrax/downloads_controller_spec.rb, spec/factories/file_download_stats.rb, spec/factories/solr_query_result.rb, spec/helpers/hyrax/work_utils_helper_spec.rb, spec/services/tasks/download_stats_migration_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1936
* Rake tasks to retrieve work data from FileDownloadStats and migration to HycDownloadStats table
* Factories for FileDownloadStats and SolrQueryResults
* Add WorkUtilityHelper to fetch work data easily by fileset id
* Small refactors for DownloadAnalyticsBehavior and related tests
=> HYC-1936 - Hyrax Cache Migration Utility

app/helpers/work_utils_helper.rb, app/services/tasks/download_stats_migration_service.rb, lib/tasks/dimensions_ingest.rake, spec/helpers/hyrax/work_utils_helper_spec.rb, spec/services/tasks/download_stats_migration_service_spec.rb
* Updated work utils helper to:
* Provide warnings if nothing is found from solr queries instead of raising errors
* Provide default param in query for admin sets 
* Changed tests to reflect changes
* Moved nil checks outside of utils helper for versatility
=> Hyrax Cache Migration Script QA

.github/workflows/build.yml, app/controllers/concerns/hyc/download_analytics_behavior.rb, app/helpers/work_utils_helper.rb, app/services/tasks/dimensions_query_service.rb, app/services/tasks/download_stats_migration_service.rb, lib/tasks/migrate_download_stats.rake, spec/controllers/hyrax/downloads_controller_spec.rb, spec/fixtures/files/matomo_stats_migration_fixture.json, spec/helpers/hyrax/work_utils_helper_spec.rb, spec/services/tasks/download_stats_migration_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1937
* Removed helpers from download analytics behavior, using ENV variables instead
* WorkUtilsHelper now makes separate queries for the work and fileset data 
* ListWorkStatInfo function now calls helpers depending on the data source in the DownloadStatsMigrationService (fetch_matomo_stats and cache_stats)
* Test class for DownloadStatsMigrationService uses a case statement to validate list_work_stat_info and migrate_to_new_table work as expected for each source
=> HYC-1937 - Expand Migration Utility to Include Matomo Stats

app/overrides/controllers/hyrax/downloads_controller_override.rb, spec/controllers/hyrax/downloads_controller_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1955
* Adjust error when trying to download a work (which is not possible) so that an Auth exception occurs instead of a 500 error
* Updates `file_set_parent` to match the base state in hyrax 4, it was previously based on hyrax 3's version of the method.
=> HYC-1955 - 500 response when downloading

.github/workflows/build.yml, Dockerfile, Gemfile, Gemfile.lock, app/overrides/jobs/attach_files_to_work_job_override.rb, app/services/tasks/dimensions_ingest_service.rb, docker-compose.yml, docker/CentOS-Base.repo, docker/start-app.sh, docker/start-sidekiq.sh, spec/features/create_article_spec.rb, spec/features/create_artwork_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_dissertation_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_multimed_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/features/create_work_in_honors_thesis_workflow_spec.rb, spec/features/edit_work_spec.rb, spec/features/set_embargo_spec.rb, spec/jobs/attach_files_to_work_job_spec.rb, spec/mailers/dimensions_report_mailer_spec.rb, spec/mailers/previews/dimensions_report_mailer_preview.rb, spec/services/tasks/dimensions_ingest_service_spec.rb, spec/services/tasks/dimensions_reporting_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1840
* Updates to using ruby 3, including syntax/language updates to code
* Updates passenger to the second most recent patch version
* Updates to docker base image to add in ruby 3, and work with the current awkward state of centos7 images
* Gems are no longer shared between sidekiq and web docker containers since this wasn't helping much and it didn't work with the necessary extra symlinking steps. Also added a check to see if bundle state was okay before installing
=> HYC-1840 - Updates for ruby 3

README.md, app/overrides/models/concerns/blacklight/document/dublin_core_override.rb, spec/models/concerns/blacklight/document/dublin_core_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1986
* Remove html tags from abstract field (displayed as "description") in OAI-PMH. The "methodology" field is not displayed, so no updates were needed for that
* Update the readme to add note about creating test database, since I keep running into that problem in the docker environment.
=> HYC-1986 - Sanitize html in OAI-PMH

Gemfile, Gemfile.lock, app/jobs/create_derivatives_job.rb, app/overrides/lib/hydra/derivatives/processors/document_override.rb, config/initializers/hyrax.rb, config/sidekiq.yml, spec/lib/hydra/derivatives/processors/document_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1988
* If an soffice run times out, the job will attempt a graceful termination, followed by a hard kill. It also now reaps the process if it was killed, to prevent defunct processes from sticking around forever
* Added a lock to soffice processing to prevent multiple runs at once, since apparently it does not support this
* Added explicit dependency on redlock, which was already getting included via hyrax
* Decreased the number of retries per job from 5 to 3, since jobs rarely recover and block up queues for long periods
* Allow soffice path to be configured from a property
=> HYC-1988 - Handle soffice pptx

solr/config/schema.xml
https://unclibrary.atlassian.net/browse/HYC-2003
Fields were still getting populated, which could cause solr to error out if fields were too long
=> HYC-2003 - Disable unused suggest fields in solr

app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/uploads/_js_templates_versioning.html.erb
https://unclibrary.atlassian.net/browse/HYC-2004
https://unclibrary.atlassian.net/browse/HYC-1942
* Disable submit button for file versions when no file has been uploaded. This prevents errors which were being logged if the user clicked the terribly labeled "Upload new version" button before uploading a new version of the file with the also terribly labeled "Choose new file version" button.
* Backport fix to prevent list of uploaded files from disappearing due to bootstrap conflict
=> HYC-2004 - File version upload fixes

app/controllers/catalog_controller.rb, app/helpers/hyc_helper.rb, app/overrides/lib/active-fedora/rdf/indexing_service_override.rb, app/renderers/hyrax/renderers/person_attribute_renderer.rb, app/services/departments_service.rb, config/authorities/departments.yml, spec/helpers/hyc_helper_spec.rb, spec/indexers/hyc_indexer_spec.rb, spec/lib/active_fedora/rdf/indexing_service_spec.rb, spec/services/departments_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1997
* Added and adjusted department vocabulary
* Fixed incorrect comma delimiters in term fields
* All solr fields will not store the id for affiliations, both in affiliation_label_tesim and in person objects.
* Facet filtering by affiliation is by id now, rather than by display form
* Affiliation values get looked up in the vocab and translated to short_labels before display, in facets and work pages
* If a department is part of a hierarchy (so it has multiple semi-colon delimited sections in the `term` field), then the affiliation_label_tesim field will now have an entry for each step of the hierarchy, rather than just the final step before.
* This means that "School of Medicine" and other top level affiliations will be listed for specific …
=> HYC-1997 - Affiliation Updates

app/services/departments_service.rb, app/services/languages_service.rb, app/services/tasks/solr_migration_service.rb, spec/services/departments_service_spec.rb, spec/services/languages_service_spec.rb, spec/services/tasks/solr_migration_service_spec.rb
* Handle Ldp:HttpError by logging it and then continuing with reindex
* Don't log vocab warning when a blank key is provided to services
=> HYC-1968 - Reindexing error handling

app/controllers/concerns/hyc/download_analytics_behavior.rb, spec/controllers/hyrax/downloads_controller_spec.rb
https://unclibrary.atlassian.net/browse/HYC-2002
It seems like setting Unknown has moved around a bunch of times, but the analytics behavior didn't get informed of the last move?
https://github.com/UNC-Libraries/hy-c/commit/bf2925f84f45dc6ad30253321040bad056fe7f2d
https://github.com/UNC-Libraries/hy-c/commit/4c583d2b450a954a9205879d04b1c93054566b3f
=> HYC-2002 - Prevent nil workdata from being added for downloads

app/renderers/hyrax/renderers/formatted_text_renderer.rb, app/services/hyrax/workflow/deposited_viewer_notification.rb, config/tinymce.yml
https://unclibrary.atlassian.net/browse/HYC-1999
- Update tinymce configuration to disable font family and color styles
- Autolink no longer sanitizes text in li_value (was removing underlines in methodology field)
- Duplicate user key caused issues running the development environment
=> HYC-1999 - Disable copy-pasted text styling in rich text fields

.github/workflows/build.yml, app/renderers/hyrax/renderers/person_attribute_renderer.rb, app/services/departments_service.rb, config/authorities/departments.yml, spec/renderers/hyrax/renderers/person_attribute_renderer_spec.rb, spec/services/departments_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-2048
* Fixes issue when displaying department with multiple terms on the full record page, like "Joint Department of Biomedical Engineering". Also fixes issue with displaying term values that don't exist in the vocab, like "North Carolina State University"
* For multi-term vocab entries like this, each term will display on its own line now
=> HYC-2048 - Fix rendering of department with multiple terms

app/assets/javascripts/hydra-editor/field_manager.es6, app/inputs/multi_value_with_unique_id_input.rb, app/views/records/edit_fields/_abstract.html.erb, spec/app/inputs/multi_value_with_unique_id_input_spec.rb
https://unclibrary.atlassian.net/browse/HYC-2009
* Overrides FieldManager in order to generate unique IDs for multivalue fields, and handles removing cloned tinymce components and then reinitializing it on new children
*  Assigns unique ids to multivalue fields at page load via new MultiValueWithUniqueIdInput input field type
=> HYC-2009 - Get tinymce to work on abstract fields after the first one

config/local_env_sample.yml
Set turnstile_enabled to true on vm. It will never get the challenge, but required for the tests to pass. Setting it in an `around` block in rspec doesn't seem to work.
=> Set turnstile_enabled to true on vm

app/views/bot_detect/challenge.html.erb
Remove noindex tag from turnstile page, which can cause google some indexing confusion
=> Remove noindex tag from turnstile page

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/helpers/query_parser_helper.rb, app/middleware/decode_query_string.rb, app/overrides/blacklight_advanced_search/advanced_query_parser_override.rb, app/search_builders/hyc/catalog_search_builder.rb, spec/blacklight_advanced_search/query_parser_spec.rb, spec/controllers/application_controller_spec.rb, spec/helpers/query_parser_helper_spec.rb, spec/middleware/decode_query_string_spec.rb, spec/search_builders/hyc/catalog_search_builder_spec.rb
https://unclibrary.atlassian.net/browse/HYC-2078
* Cleanup unbalanced quotes and parenthesis when generating advanced search queries, otherwise we get Parslet errors for search terms like `hello"`
* Add better logging of unhandled exceptions, so we can see the full backtrace rather than cutting off at the middleware
* Update to blacklight 7.40 (was 7.37 via a fork)
=> HYC-2078 - Fix advanced search with unbalanced quotes

app/helpers/work_utils_helper.rb, app/services/tasks/ingest_helper.rb, spec/helpers/hyrax/work_utils_helper_spec.rb, spec/services/tasks/ingest_helper_spec.rb, spec/services/tasks/pubmed_ingest/pubmed_ingest_coordinator_service_spec.rb
Persist works before fileset attachment
[Bug](https://splunk.unc.edu/en-US/app/libraries/search?display.page.search.mode=fast&dispatch.sample_ratio=1&q=search%20host%3D%22toronto.lib.unc.edu%22%20source%3D%22%2Flogs%2Fhyc%2Fproduction.log%22%20%22Error%20performing%20FileSetAttachedEventJob%22%20%22Job%20ID%3A%20fa903a7a-0981-4bd9-be69-eff47e990f07%22&earliest=%40d&latest=now&display.page.search.tab=events&display.general.type=events&sid=1750947921.10696_AB41F19C-07AA-4E0B-B3CD-26C769C8434C)
=> HYC 2066 Follow Up 
