app/forms/hyrax/general_form.rb, app/helpers/hyrax/citations_behaviors/formatters/apa_formatter.rb, spec/forms/hyrax/general_form_spec.rb
Only the APA format seems to require an author
=> Fix citations so they work with author-less works

app/assets/javascripts/unc_custom.js, app/assets/stylesheets/unc_custom.css.scss
1. Addresses https://jira.lib.unc.edu/browse/HYC-159
2. Addresses https://jira.lib.unc.edu/browse/HYC-164
3. Also fixes the date picker occasionally appearing behind input fields  https://jira.lib.unc.edu/browse/HYC-165
=> Hide calendar and add future dates for embargoes

app/assets/javascripts/application.js, app/assets/javascripts/unc_custom.js
1. Addresses https://jira.lib.unc.edu/browse/HYC-153 (turbolinks error)
2. Addresses https://jira.lib.unc.edu/browse/HYC-167
3. Addresses https://jira.lib.unc.edu/browse/HYC-169
4. Should address @bbpennel comments on #53 (Probably better to let assets pipeline deal with JS)
=> Add turbolinks and make sure datepicker works with it.

app/assets/stylesheets/unc_custom.css.scss
https://jira.lib.unc.edu/browse/HYC-180
=> Agreement styling

app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/base/_citations.html.erb, config/locales/article.en.yml
https://jira.lib.unc.edu/browse/HYC-168
=> differentiate between citations and downloads for citation services

app/assets/javascripts/unc_custom.js, app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/homepage/_featured.html.erb, app/views/hyrax/homepage/_featured_fields.html.erb, app/views/hyrax/homepage/_featured_works.html.erb, app/views/hyrax/homepage/_home_content.html.erb
The way it's setup at the moment we need to always have 3 featured works, so the spacing looks okay. It also centers everything vertically per Hong's suggestion.
=> Featured works on homepage

config/authorities/resource_types.yml
https://jira.lib.unc.edu/browse/HYC-191
=> Update resource type terms

app/views/hyrax/notifications/_notifications.html.erb
https://jira.lib.unc.edu/browse/HYC-227
=> Show newest messages first

config/solr.yml, solr/config/solrconfig.xml
https://jira.lib.unc.edu/browse/HYC-245
* Updates location of solr installation/instance directory so solr can find jar files on ir-qa
=> Hyc 245 pdfbox error

app/controllers/hyrax/articles_controller.rb, app/forms/hyrax/honors_thesis_form.rb, app/forms/single_value_form.rb, app/jobs/assign_permissions_to_work_job.rb, app/services/hyrax/workflow/assign_reviewer_by_academic_department.rb, app/services/hyrax/workflow/assign_reviewer_by_affiliation.rb, app/views/hyrax/articles/_attribute_rows.html.erb, app/views/hyrax/base/_form_relationships.html.erb, app/views/hyrax/dissertations/_attribute_rows.html.erb, app/views/hyrax/generals/_attribute_rows.html.erb, app/views/hyrax/honors_theses/_attribute_rows.html.erb, app/views/hyrax/masters_papers/_attribute_rows.html.erb, app/views/records/edit_fields/_academic_concentration.html.erb, app/views/records/edit_fields/_affiliation.html.erb, config/workflows/honors_thesis_deposit_workflow.json, lib/tasks/admin_role.rake, lib/tasks/new_user.rake, spec/features/create_article_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/features/create_work_in_honors_thesis_workflow_spec.rb, spec/features/edit_work_spec.rb, spec/forms/hyrax/honors_thesis_form_spec.rb
* Make affiliation required and single-valued in honors thesis form
* Remove requirement for academic concentration from honors thesis form
* Add feature test for reviewer group creation for honors thesis workflow
=> Honors workflow

app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
https://jira.lib.unc.edu/browse/HYC-212
=> Allow only admins to see link to admin sets

app/services/parent_query_service.rb, app/views/hyrax/base/_parent_relationship_table.html.erb, app/views/hyrax/base/_relationships_parent_rows.html.erb, app/views/hyrax/base/_show_actions.html.erb, config/locales/hyrax.en.yml, spec/services/parent_query_service_spec.rb
Implements OSU way of adding parent links, but don't see any records that actually have parents.
https://jira.lib.unc.edu/browse/HYC-204
=> Add link to parent when viewing child work

app/controllers/catalog_controller.rb
https://jira.lib.unc.edu/browse/HYC-256
=> Add version and remove publisher facet

config/initializers/hyrax.rb
* Need to use the default branding image path
=> Remove custom branding image path from config

app/presenters/hyrax/workflow_presenter.rb, app/views/hyrax/base/_items.html.erb, app/views/hyrax/base/_show_actions.html.erb, app/views/hyrax/file_sets/media_display/_audio.html.erb, app/views/hyrax/file_sets/media_display/_default.html.erb, app/views/hyrax/file_sets/media_display/_image.html.erb, app/views/hyrax/file_sets/media_display/_office_document.html.erb, app/views/hyrax/file_sets/media_display/_pdf.html.erb, app/views/hyrax/file_sets/media_display/_video.html.erb, config/workflows/default_workflow.json, config/workflows/honors_thesis_deposit_workflow.json, config/workflows/mediated_deposit_workflow.json, spec/presenters/hyrax/workflow_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-264
=> Change workflow state name

Gemfile, Gemfile.lock, app/assets/javascripts/hyrax/ga_events.js, app/controllers/concerns/hyc/download_analytics_behavior.rb, app/controllers/hyc/downloads_controller.rb, spec/controllers/hyc/downloads_controller_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
Reverts UNC-Libraries/hy-c#103
=> Revert "Remove download add-ons"

app/models/masters_paper.rb, spec/features/create_article_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_dissertation_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_multimed_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/forms/hyrax/masters_paper_form_spec.rb
* Made affiliations multi-valued for masters papers
* Updated masters papers form test
* Added check of edit pages in feature tests to catch these types of errors in the future
=> Hyc 281 edit masters paper

app/assets/stylesheets/unc_custom.css.scss, app/presenters/hyrax/workflow_presenter.rb, app/views/hyrax/base/show.html.erb, config/workflows/art_mfa_deposit_workflow.json, spec/presenters/hyrax/workflow_presenter_spec.rb
Also display message to add child works
https://jira.lib.unc.edu/browse/HYC-273
=> Create Art MFA workflow

app/assets/javascripts/unc/unc_visibility_component.es6
https://jira.lib.unc.edu/browse/HYC-290
=> Select least restrictive allowed option

app/actors/hyrax/actors/interpret_visibility_actor.rb
https://jira.lib.unc.edu/browse/HYC-262
=> Allow admins to create embargoes in admin sets that don't allow it

app/views/hyrax/dashboard/sidebar/_configuration.html.erb, app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
https://jira.lib.unc.edu/browse/HYC-292
=> Update Sidebar Link Text

app/views/records/edit_fields/_resource_type.html.erb, spec/features/create_article_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_masters_paper_spec.rb
https://jira.lib.unc.edu/browse/HYC-287
=> Fix Resource Type Not Being Auto Selected for Work Types

spec/features/create_art_work_spec.rb
Files tab was collapsed into Description tab after this pull request was made. Updating tests to reflect updates
=> Fix tests to reflect code changes since pull request was made

config/authorities/resource_types.yml
https://jira.lib.unc.edu/browse/HYC-296
=> Add "Art" Resource Type

app/views/hyrax/base/_show_actions.html.erb
https://jira.lib.unc.edu/browse/HYC-276
=> Art MFA Child Works

app/assets/javascripts/unc/unc_custom.js, app/controllers/hyrax/generals_controller.rb, app/views/shared/_select_work_type_modal.html.erb, spec/features/create_general_spec.rb, spec/features/select_work_type_modal_spec.rb
https://jira.lib.unc.edu/browse/HYC-303
=> Hide general, dissertation and art mfa worktypes from non-admins

Gemfile, Gemfile.lock, app/views/roles/edit.html.erb
Update hydra-role-management gem and make sure right version of edit partial is there
https://jira.lib.unc.edu/browse/HYC-161
=> Update hydra-role-management gem

app/views/hyrax/notifications/_notifications.html.erb
https://jira.lib.unc.edu/browse/HYC-289
=> Sort by timestamp so messages always show the most recent first

app/controllers/accounts_controller.rb, app/models/user.rb, app/views/accounts/new.html.erb
https://jira.lib.unc.edu/browse/HYC-301
=> Switch to onyen instead of email for new users

config/locales/hyrax.en.yml
https://jira.lib.unc.edu/browse/HYC-309
=> Update dropdown search text

app/assets/javascripts/unc/unc_custom.js, app/views/shared/_select_work_type_modal.html.erb
Small fix to hide Art Work form. It was checking for the wrong string value
=> Check for correct art work label

app/assets/stylesheets/unc_custom.css.scss, app/views/catalog/_constraints.html.erb
https://jira.lib.unc.edu/browse/HYC-308
=> Add header on "Collections" page and don't show constraints

app/assets/javascripts/unc/unc_custom.js
Small fix, not associated with a ticket
=> Check that functions work with turbolinks

config/initializers/hyrax.rb
https://jira.lib.unc.edu/browse/HYC-241
Depends on: https://gitlab.lib.unc.edu/cdr/vagrant-rails/merge_requests/34
=> Setup geonames

app/views/hyrax/base/_items.html.erb, app/views/records/edit_fields/_resource_type.html.erb, config/locales/hyrax.en.yml, spec/features/create_art_work_spec.rb
https://jira.lib.unc.edu/browse/HYC-311
https://jira.lib.unc.edu/browse/HYC-312
=> Text updates for art work type

spec/features/create_art_work_spec.rb
Causing other pull requests to fail, since these are broken
=> Fix missed Art work type tests

app/controllers/hyrax/users_controller.rb, app/jobs/file_set_attached_event_job.rb, app/views/hyrax/file_sets/_show_details.html.erb, config/routes.rb
https://jira.lib.unc.edu/browse/HYC-323
=> Restrict user profiles to admins

app/controllers/catalog_controller.rb, app/views/catalog/_index_list_default.html.erb
Restrict which fields to show in search results and truncate long field values
https://jira.lib.unc.edu/browse/HYC-313
=> Restrict fields shown in search results

config/routes.rb
https://jira.lib.unc.edu/browse/HYC-327
=> Add catch all route

app/assets/javascripts/unc/unc_visibility_component.es6
https://jira.lib.unc.edu/browse/HYC-328
=> Fix issue with all saved records trying to save as "Public"

config/routes.rb
https://jira.lib.unc.edu/browse/HYC-326
=> Remove routes for actions we don't use

.travis.yml
https://jira.lib.unc.edu/browse/HYC-330
=> Update travis configs

config/browse_everything_providers.yml
Disables Browse Everything from adding files directly from the file system
=> disable file system access

app/services/hyrax/workflow/assign_reviewer_by_affiliation.rb, config/workflows/honors_thesis_deposit_workflow.json
https://jira.lib.unc.edu/browse/HYC-285
I think this should work. Would need to test on QA
=> Reassign reviewer after depositor finishes making requested changes.

lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/metadata_parser.rb, spec/tasks/migrate_rake_spec.rb
https://jira.lib.unc.edu/browse/HYC-314
=> Add label fields to migration script

app/views/records/edit_fields/_subject.html.erb
https://jira.lib.unc.edu/browse/HYC-346
=> enable FAST integration

app/forms/hyrax/artwork_form.rb, app/models/artwork.rb, app/presenters/hyrax/artwork_presenter.rb, app/views/hyrax/artworks/_attribute_rows.html.erb, config/locales/artwork.en.yml, spec/features/create_artwork_spec.rb, spec/forms/hyrax/artwork_form_spec.rb, spec/models/artwork_spec.rb, spec/presenters/hyrax/artwork_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-341
=> Art Form Field Updates

app/controllers/catalog_controller.rb, app/jobs/content_delete_event_job.rb, app/jobs/content_deposit_event_job.rb, app/jobs/content_depositor_change_event_job.rb, app/jobs/content_new_version_job.rb, app/jobs/content_restored_version_event_job.rb, app/jobs/content_update_event_job.rb, app/jobs/file_set_attached_event_job.rb, app/models/user.rb, app/views/hyrax/admin/admin_sets/_show_document_list_row.html.erb, app/views/hyrax/admin/stats/_top_data.html.erb, app/views/hyrax/base/_form_share.html.erb, app/views/hyrax/dashboard/collections/_show_document_list_row.html.erb, app/views/hyrax/file_sets/_permission_form.html.erb, app/views/hyrax/file_sets/_show_details.html.erb, app/views/hyrax/users/_proxies.html.erb, spec/models/user_spec.rb
https://jira.lib.unc.edu/browse/HYC-343
=> Get rid of links to user profiles for depositor search

app/views/hyrax/base/_form_metadata.html.erb
https://jira.lib.unc.edu/browse/HYC-352
=> Move technical image metadata to the bottom of the form

app/views/hyrax/base/_show_actions.html.erb
https://jira.lib.unc.edu/browse/HYC-351
=> Hide admin only and speciality form links from non-admins

app/views/default_admin_sets/_form.html.erb, spec/features/edit_default_admin_set_spec.rb
https://jira.lib.unc.edu/browse/HYC-284
=> Use masters papers service for admin set dept form

config/environments/production.rb
https://jira.lib.unc.edu/browse/HYC-277
Depends upon https://gitlab.lib.unc.edu/cdr/vagrant-rails/merge_requests/39
=> Move production logs out of deployment directory

app/controllers/hyrax/depositors_controller.rb, app/models/proxy_deposit_request.rb, app/services/hyrax/batch_create_failure_service.rb, app/services/hyrax/batch_create_success_service.rb, app/services/hyrax/fixity_check_failure_service.rb, app/services/hyrax/import_url_failure_service.rb, app/services/hyrax/workflow/abstract_notification.rb, app/services/hyrax/workflow/changes_required_notification.rb, app/services/hyrax/workflow/deletion_approval_notification.rb, app/services/hyrax/workflow/deletion_request_rejection_notification.rb, app/services/hyrax/workflow/deposited_notification.rb, app/services/hyrax/workflow/pending_deletion_notification.rb, app/services/hyrax/workflow/pending_review_notification.rb, config/locales/hyrax.en.yml, spec/services/hyrax/workflow/deletion_approval_notification_spec.rb, spec/services/hyrax/workflow/deletion_request_rejection_notification_spec.rb, spec/services/hyrax/workflow/pending_deletion_notification_spec.rb
https://jira.lib.unc.edu/browse/BXC-2293
=> Update email text

config/locales/hyrax.en.yml, spec/features/create_article_spec.rb, spec/features/create_artwork_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_dissertation_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_multimed_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/features/create_work_in_honors_thesis_workflow_spec.rb, spec/features/edit_work_spec.rb, spec/features/set_embargo_spec.rb
https://jira.lib.unc.edu/browse/HYC-380
=> Update tab text

app/forms/single_value_form.rb, lib/active_fedora/rdf/indexing_service.rb, spec/jobs/assign_permissions_to_work_job_spec.rb
https://jira.lib.unc.edu/browse/HYC-383
=> Maintain affiliation ordering

app/assets/javascripts/hyrax/save_work/required_fields.es6, app/assets/javascripts/person_objects.js, app/assets/javascripts/unc/unc_custom.js, app/assets/javascripts/unc/unc_save_work_control.es6, app/assets/stylesheets/unc_custom.css.scss, app/forms/hyrax/honors_thesis_form.rb, app/models/honors_thesis.rb, app/views/records/edit_fields/_person.html.erb, spec/forms/hyrax/honors_thesis_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-368
=> Make sure required people object fields are required

app/assets/javascripts/person_objects.js
https://jira.lib.unc.edu/browse/HYC-386
=> Fix issue with people objects being dropped if more than 2 are present

app/models/user.rb, spec/models/user_spec.rb
https://jira.lib.unc.edu/browse/HYC-392
=> Create new user with onyen@ad.unc.edu email address if none in shibboleth response

app/controllers/concerns/hyc/download_analytics_behavior.rb, app/controllers/hyc/downloads_controller.rb
https://jira.lib.unc.edu/browse/HYC-382
https://jira.lib.unc.edu/browse/HYC-381
=> Add admin set to GA category

app/search_builders/hyrax/my/search_builder.rb
https://jira.lib.unc.edu/browse/HYC-192
=> Allow admins to attach children owned by other users

config/locales/hyrax.en.yml
https://jira.lib.unc.edu/browse/HYC-388
=> Update text for institution restriction

app/controllers/concerns/hyc/download_analytics_behavior.rb
https://jira.lib.unc.edu/browse/HYC-397
https://jira.lib.unc.edu/browse/HYC-398
=> Update action and category text

app/forms/hyrax/article_form.rb, app/forms/hyrax/artwork_form.rb, app/forms/hyrax/dissertation_form.rb, app/forms/hyrax/general_form.rb, app/forms/hyrax/journal_form.rb, app/forms/hyrax/scholarly_work_form.rb, spec/features/create_article_spec.rb, spec/features/create_artwork_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/forms/hyrax/article_form_spec.rb, spec/forms/hyrax/dissertation_form_spec.rb, spec/forms/hyrax/general_form_spec.rb, spec/forms/hyrax/journal_form_spec.rb, spec/forms/hyrax/scholarly_work_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-390
=> Make DOI admin only

app/models/deposit_record.rb, lib/tasks/deposit_record/migrate.rake
https://jira.lib.unc.edu/browse/HYC-396
=> Remove old uuid from new deposit record

app/models/scholarly_work.rb, config/locales/scholarly_work.en.yml, spec/features/create_scholarly_work_spec.rb
https://jira.lib.unc.edu/browse/HYC-389
=> Change work type human readable name

lib/tasks/migrate/migration_config.yml, lib/tasks/migrate/services/ingest_service.rb
https://jira.lib.unc.edu/browse/HYC-395
=> Log data lost in migration

app/assets/stylesheets/unc_custom.css.scss, app/views/records/edit_fields/_resource_type.html.erb
https://jira.lib.unc.edu/browse/HYC-393
=> Adjust multi-select box size

app/models/auth_config.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, lib/devise/parameter_sanitizer.rb
https://jira.lib.unc.edu/browse/HYC-400
=> Devise signup link

app/models/proxy_deposit_request.rb, config/locales/hyrax.en.yml
https://jira.lib.unc.edu/browse/HYC-211
=> Fix transfer message

app/assets/javascripts/unc/unc_custom.js, app/views/hyrax/homepage/_unc_deposit.html.erb
https://jira.lib.unc.edu/browse/HYC-394
=> Only show subset of forms in "other deposits" option

app/actors/hyrax/actors/file_set_actor.rb, app/uploaders/hyrax/uploaded_file_uploader.rb, lib/tasks/migrate/services/ingest_service.rb
https://jira.lib.unc.edu/browse/HYC-371
https://jira.lib.unc.edu/browse/HYC-179
=> File versioning with perform now

config/workflows/honors_thesis_deposit_workflow.json, spec/features/create_work_in_honors_thesis_workflow_spec.rb
https://jira.lib.unc.edu/browse/HYC-405
=> Honors workflow visibility

app/assets/javascripts/person_objects.js, app/views/records/edit_fields/_person.html.erb, spec/features/create_article_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_dissertation_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_multimed_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/features/create_work_in_honors_thesis_workflow_spec.rb, spec/features/edit_work_spec.rb, spec/features/set_embargo_spec.rb
https://jira.lib.unc.edu/browse/HYC-401
=> Numbering People Objects

app/views/hyrax/base/show.html.erb
https://jira.lib.unc.edu/browse/HYC-426
=> Update message for adding child artworks

app/views/hyrax/file_sets/media_display/_audio.html.erb, app/views/hyrax/file_sets/media_display/_default.html.erb, app/views/hyrax/file_sets/media_display/_image.html.erb, app/views/hyrax/file_sets/media_display/_office_document.html.erb, app/views/hyrax/file_sets/media_display/_pdf.html.erb, app/views/hyrax/file_sets/media_display/_video.html.erb
Show download link for any work that isn't withdrawn or pending withdrawal.
https://jira.lib.unc.edu/browse/HYC-427
=> Show download link for any work that isn't withdrawn

app/forms/hyrax/article_form.rb, app/views/hyrax/articles/_attribute_rows.html.erb, spec/features/create_article_spec.rb, spec/forms/hyrax/article_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-430
=> Article form updates

app/forms/hyrax/journal_form.rb, spec/features/create_journal_spec.rb, spec/forms/hyrax/journal_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-431
=> Journal form updates

app/forms/hyrax/honors_thesis_form.rb, app/views/records/edit_fields/_graduation_year.html.erb, spec/features/create_honors_thesis_spec.rb, spec/forms/hyrax/honors_thesis_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-428
=> Honors form updates

app/forms/hyrax/multimed_form.rb, spec/features/create_multimed_spec.rb, spec/forms/hyrax/multimed_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-432
=> Multimedia form updates

app/forms/hyrax/scholarly_work_form.rb, spec/features/create_scholarly_work_spec.rb, spec/forms/hyrax/scholarly_work_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-434
=> Scholarly works form updates

app/views/records/edit_fields/_graduation_year.html.erb, config/locales/hyrax.en.yml
https://jira.lib.unc.edu/browse/HYC-429
=> Masters papers form updates

app/forms/hyrax/data_set_form.rb, config/authorities/licenses.yml, spec/features/create_data_set_spec.rb, spec/forms/hyrax/data_set_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-435
=> Dataset form updates

config/workflows/art_mfa_deposit_workflow.json, config/workflows/honors_thesis_deposit_workflow.json, config/workflows/mediated_deposit_workflow.json
https://jira.lib.unc.edu/browse/HYC-406
=> Allow sharing in workflows

config/locales/hyrax.en.yml
https://jira.lib.unc.edu/browse/HYC-440
=> Update messages to show username

app/views/hyrax/my/_work_action_menu.html.erb, app/views/hyrax/my/works/_default_group.html.erb, app/views/hyrax/my/works/_list_works.html.erb
https://jira.lib.unc.edu/browse/HYC-448
=> Remove option to feature work on user's profile

app/inputs/multi_value_input.rb
https://jira.lib.unc.edu/browse/HYC-439
=> Allow HTML5 date display in multi-value fields

app/forms/hyrax/journal_form.rb, app/models/journal.rb, app/presenters/hyrax/journal_presenter.rb, app/views/hyrax/journals/_attribute_rows.html.erb, spec/features/create_journal_spec.rb, spec/forms/hyrax/journal_form_spec.rb, spec/models/journal_spec.rb, spec/presenters/hyrax/journal_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-461
=> Add series field to journal work type

app/assets/stylesheets/unc_custom.css.scss
https://jira.lib.unc.edu/browse/HYC-469
=> HYC-469 - Remove white border under banner

app/controllers/application_controller.rb, lib/redirects/redirect_uuids.csv
https://jira.lib.unc.edu/browse/BXC-2319
Related to https://gitlab.lib.unc.edu/cdr/vagrant-rails/merge_requests/54
=> Box-c to hy-c redirects

config/workflows/honors_thesis_deposit_workflow.json, spec/features/create_work_in_honors_thesis_workflow_spec.rb
https://jira.lib.unc.edu/browse/HYC-441
=> Have approvers get review emails

app/views/hyrax/dashboard/sidebar/_activity.html.erb
https://jira.lib.unc.edu/browse/HYC-474
=> Remove user profile link from dashboard

config/locales/hyrax.en.yml, spec/features/create_article_spec.rb, spec/features/create_artwork_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_dissertation_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_multimed_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/features/create_work_in_honors_thesis_workflow_spec.rb, spec/features/edit_work_spec.rb, spec/features/set_embargo_spec.rb
https://jira.lib.unc.edu/browse/HYC-475
=> Update product name for title tag

config/workflows/art_mfa_deposit_workflow.json, config/workflows/default_workflow.json, config/workflows/honors_thesis_deposit_workflow.json, config/workflows/mediated_deposit_workflow.json, spec/features/create_work_in_honors_thesis_workflow_spec.rb
https://jira.lib.unc.edu/browse/HYC-476
=> Have depositors always receive a notification on deposit

config/workflows/manager_default_workflow.json
https://jira.lib.unc.edu/browse/HYC-477
=> Default workflow with manager emails

app/controllers/application_controller.rb
https://jira.lib.unc.edu/browse/HYC-490
Collections is a valid path in both box-c and hy-c.
=> Allow collections through url filter

config/application.rb
https://jira.lib.unc.edu/browse/HYC-466
=> Read settings from an ENV variable

app/forms/single_value_form.rb
https://jira.lib.unc.edu/browse/HYC-491
=> Allow languages and licenses to be overwritten by new values

app/views/records/edit_fields/_date_created.html.erb, app/views/records/edit_fields/_date_issued.html.erb, app/views/records/edit_fields/_degree_granting_institution.html.erb, app/views/records/edit_fields/_graduation_year.html.erb, app/views/records/edit_fields/_last_modified_date.html.erb
https://jira.lib.unc.edu/browse/HYC-497
=> Only auto-fill dates for new submissions

config/authorities/departments.yml
https://jira.lib.unc.edu/browse/HYC-507
=> Add more departments

config/authorities/degrees.yml
https://jira.lib.unc.edu/browse/HYC-502
=> Add new degrees

app/lib/hydra/derivatives/processors/document.rb
Resolves: https://jira.lib.unc.edu/browse/HYC-487
=> HYC487 - PDF No such file or directory

.travis.yml, config/initializers/hyrax.rb
Requires https://gitlab.lib.unc.edu/cdr/vagrant-rails/merge_requests/59 to be merged
Resolves https://jira.lib.unc.edu/browse/HYC-485
=> Switch temp dir to TEMP_STORAGE

config/authorities/academic_concentration.yml
https://jira.lib.unc.edu/browse/HYC-505
=> Add new masters papers concentrations

lib/tasks/migrate/services/metadata_parser.rb
https://jira.lib.unc.edu/browse/HYC-464
=> Migrate dates and terms of address with names

public/robots.txt
https://jira.lib.unc.edu/browse/HYC-423
Disallow crawling searches, oai, and stats pages
=> Customize robots.txt

app/models/general.rb, lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/metadata_parser.rb, spec/models/general_spec.rb, spec/tasks/migrate_rake_spec.rb
https://jira.lib.unc.edu/browse/HYC-515
=> Attach metadata file

config/environments/development.rb, config/environments/production.rb
https://jira.lib.unc.edu/browse/HYC-512
=> Customize log messages and tone down production logging

app/services/awards_service.rb, app/services/degrees_service.rb, app/views/records/edit_fields/_award.html.erb, app/views/records/edit_fields/_degree.html.erb, config/authorities/awards.yml, config/authorities/degrees.yml, lib/tasks/migrate/services/metadata_parser.rb, spec/fixtures/authorities/awards.yml, spec/fixtures/authorities/degrees.yml, spec/services/awards_service_spec.rb, spec/services/degrees_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-508
=> Legacy mappings for Box-C to Hy-C migration

config/workflows/honors_thesis_deposit_workflow.json, spec/features/create_work_in_honors_thesis_workflow_spec.rb
fixing problems created by merging the wrong PR
=> Honors workflow update

app/jobs/register_to_longleaf_job.rb
Part of https://jira.lib.unc.edu/browse/LEF-24
=> LEF-24 - Add checksum while registering file to longleaf

app/controllers/hyrax/dissertations_controller.rb, app/controllers/hyrax/generals_controller.rb
https://jira.lib.unc.edu/browse/HYC-521
https://jira.lib.unc.edu/browse/HYC-523
=> Some public works give authorization errors

app/services/hyrax/workflow/changes_required_notification.rb, app/services/hyrax/workflow/deletion_approval_notification.rb, app/services/hyrax/workflow/deletion_request_rejection_notification.rb, app/services/hyrax/workflow/deposit_approved_notification.rb, app/services/hyrax/workflow/deposited_manager_notification.rb, app/services/hyrax/workflow/deposited_notification.rb, app/services/hyrax/workflow/mediated_deposit_notification.rb, app/services/hyrax/workflow/virus_found_notification.rb, config/locales/hyrax.en.yml, config/workflows/art_mfa_deposit_workflow.json, config/workflows/manager_default_workflow.json, config/workflows/mediated_deposit_workflow.json, lib/tasks/clear_notifiable_contexts.rake, spec/services/hyrax/workflow/deletion_approval_notification_spec.rb, spec/services/hyrax/workflow/deletion_request_rejection_notification_spec.rb, spec/services/hyrax/workflow/deposited_manager_notification_spec.rb
https://jira.lib.unc.edu/browse/HYC-516
=> Workflow notifications

app/controllers/catalog_controller.rb, app/forms/hyrax/general_form.rb, app/forms/hyrax/journal_form.rb, app/models/article.rb, app/models/general.rb, app/models/journal.rb, app/models/solr_document.rb, app/presenters/hyrax/general_presenter.rb, app/presenters/hyrax/journal_presenter.rb, app/views/hyrax/articles/_attribute_rows.html.erb, app/views/hyrax/generals/_attribute_rows.html.erb, app/views/hyrax/journals/_attribute_rows.html.erb, config/locales/hyrax.en.yml, lib/tasks/migrate/services/metadata_parser.rb, spec/features/create_general_spec.rb, spec/features/create_journal_spec.rb, spec/forms/hyrax/general_form_spec.rb, spec/forms/hyrax/journal_form_spec.rb, spec/models/general_spec.rb, spec/models/journal_spec.rb, spec/presenters/hyrax/general_presenter_spec.rb, spec/presenters/hyrax/journal_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-518
=> Check form map fields

lib/tasks/migrate/migrate.rake, lib/tasks/migrate/services/child_work_parser.rb, lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/metadata_parser.rb
https://jira.lib.unc.edu/browse/HYC-498
* migrate primary objects as filesets in hyrax
* example: https://ir-test.lib.unc.edu/concern/journals/dv13zv83d?locale=en
=> Hyc 498 primary objects

lib/tasks/migrate/services/metadata_parser.rb
https://jira.lib.unc.edu/browse/HYC-536
=> Migrate list of unique affiliations for each person

app/forms/hyrax/artwork_form.rb, app/models/artwork.rb, app/presenters/hyrax/artwork_presenter.rb, app/views/hyrax/artworks/_attribute_rows.html.erb, spec/features/create_artwork_spec.rb, spec/forms/hyrax/artwork_form_spec.rb, spec/models/artwork_spec.rb, spec/presenters/hyrax/artwork_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-538
=> Add creator to artwork form

app/forms/hyrax/dissertation_form.rb, app/models/dissertation.rb, app/presenters/hyrax/dissertation_presenter.rb, app/views/hyrax/dissertations/_attribute_rows.html.erb, lib/tasks/proquest_ingest.rake, spec/features/create_dissertation_spec.rb, spec/forms/hyrax/dissertation_form_spec.rb, spec/models/dissertation_spec.rb, spec/presenters/hyrax/dissertation_presenter_spec.rb, spec/tasks/proquest_ingest_rake_spec.rb
https://jira.lib.unc.edu/browse/HYC-547
=> Remove academic concentration from dissertation work type

app/indexers/article_indexer.rb, app/indexers/artwork_indexer.rb, app/indexers/data_set_indexer.rb, app/indexers/dissertation_indexer.rb, app/indexers/general_indexer.rb, app/indexers/honors_thesis_indexer.rb, app/indexers/hyc_indexer.rb, app/indexers/journal_indexer.rb, app/indexers/masters_paper_indexer.rb, app/indexers/multimed_indexer.rb, app/indexers/scholarly_work_indexer.rb, app/views/hyrax/articles/_attribute_rows.html.erb, app/views/hyrax/artworks/_attribute_rows.html.erb, app/views/hyrax/data_sets/_attribute_rows.html.erb, app/views/hyrax/dissertations/_attribute_rows.html.erb, app/views/hyrax/generals/_attribute_rows.html.erb, app/views/hyrax/honors_theses/_attribute_rows.html.erb, app/views/hyrax/journals/_attribute_rows.html.erb, app/views/hyrax/masters_papers/_attribute_rows.html.erb, app/views/hyrax/multimeds/_attribute_rows.html.erb, app/views/hyrax/scholarly_works/_attribute_rows.html.erb
https://jira.lib.unc.edu/browse/HYC-557
=> Add custom indexing to humanize dates in search results

lib/active_fedora/rdf/indexing_service.rb
https://jira.lib.unc.edu/browse/HYC-568
=> Facet creators, advisors, and affiliations

app/views/hyrax/my/_search_form.html.erb
https://jira.lib.unc.edu/browse/HYC-570
=> Allow all metadata to be used in searches for works in the dashboard

app/indexers/hyc_indexer.rb
https://jira.lib.unc.edu/browse/HYC-572
=> Add check to see if there's a value before indexing

app/helpers/blacklight/facets_helper_behavior.rb
Can probably throw this in as part of https://jira.lib.unc.edu/browse/HYC-557
=>  Convert date facet display from EDTF to human readable strings

Gemfile, Gemfile.lock
https://jira.lib.unc.edu/browse/HYC-548
See also:
https://gitlab.lib.unc.edu/cdr/hyc-gems/merge_requests/13
https://gitlab.lib.unc.edu/cdr/vagrant-rails/merge_requests/67
=> HYC-548 - Remove longleaf dependency

lib/tasks/deposit_record/migrate.rake
Updates made to the deposit record migration rake task in order to recover from errors
=> Deposit record updates

app/indexers/hyrax/deep_indexing_service.rb
Small fix to remove empty location fields so unnecessary trailing commas aren't displayed
https://jira.lib.unc.edu/browse/HYC-595
=> Small fix to remove empty location fields

app/views/_controls.html.erb, app/views/hyrax/homepage/_unc_masthead.html.erb, config/locales/hyrax.en.yml
https://jira.lib.unc.edu/browse/HYC-594
=> Add browse everything button and update collections text

lib/tasks/migrate/services/ingest_service.rb
* https://jira.lib.unc.edu/browse/HYC-598
* create sipity entities for migrated works
* only need to save the new work once
=> Migrate works into an active workflow

app/lib/qa/authorities/local/file_based_authority.rb, app/services/academic_concentration_service.rb, app/services/degrees_service.rb, app/views/records/edit_fields/_degree.html.erb, config/authorities/academic_concentration.yml, config/authorities/degrees.yml, spec/features/create_dissertation_spec.rb, spec/fixtures/authorities/academic_concentration.yml, spec/fixtures/authorities/degrees.yml, spec/services/degrees_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-600
=> Allow custom keys for Questioning Authority vocabularies

lib/active_fedora/rdf/indexing_service.rb, spec/fixtures/oai_sample_documents.yml
* https://jira.lib.unc.edu/browse/HYC-606
* reinstating solr indexing of dates as human readable
=> Hyc 606 collection dates

app/controllers/catalog_controller.rb
https://jira.lib.unc.edu/browse/HYC-605
=> Remove date created from search display

app/views/records/edit_fields/_person.html.erb
https://jira.lib.unc.edu/browse/HYC-603
=> Make affiliation required for creator, but not advisor in honors form

lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/metadata_parser.rb
* https://jira.lib.unc.edu/browse/HYC-607
=> deduplicated values

app/controllers/concerns/hydra/controller/download_behavior.rb, app/services/mime_type_service.rb, spec/fixtures/authorities/mime_types.yml, spec/services/admin_set_select_service_spec.rb, spec/services/mime_type_service_spec.rb
* https://jira.lib.unc.edu/browse/HYC-604
=> mime type check

.travis.yml, app/services/hyrax/workflow/abstract_notification.rb, app/services/hyrax/workflow/notification_service.rb, config/environments/production.rb
* https://jira.lib.unc.edu/browse/HYC-415
* turn off emails and in-app notifications for the migration
* tests will fail
=> turn off emails

app/forms/hyrax/forms/collection_form.rb
https://jira.lib.unc.edu/browse/HYC-620
=> Remove geonames (:based_near) from collections form

app/views/hyrax/base/_form_progress.html.erb
Form won't work if something isn't submitted, so just hide it.
https://jira.lib.unc.edu/browse/HYC-624
=> Don't have admins check agreement box on edit

app/views/hyrax/base/_social_media.html.erb
https://jira.lib.unc.edu/browse/HYC-637
=> Remove social media buttons

app/views/shared/_footer_social.html.erb
https://jira.lib.unc.edu/browse/HYC-641
=> Remove default twitter text

app/models/concerns/blacklight/document/dublin_core.rb, app/models/concerns/hyrax/blacklight/document/dublin_core.rb, app/models/solr_document.rb
* https://jira.lib.unc.edu/browse/HYC-609
=> oai feed updates

config/authorities/degrees.yml
https://jira.lib.unc.edu/browse/HYC-651
=> Add honors degrees

app/assets/stylesheets/unc_custom.css.scss, app/views/layouts/hyrax.html.erb
https://jira.lib.unc.edu/browse/HYC-652
=> Add padding for large screens

app/assets/javascripts/hyrax/save_work/deposit_agreement.es6, app/views/hyrax/base/_form_progress.html.erb
https://jira.lib.unc.edu/browse/HYC-655
=> Allow admins to add files when editing

config/initializers/hyrax.rb
* https://jira.lib.unc.edu/browse/HYC-635
=> Use the temp storage location for the working path

app/jobs/create_derivatives_job.rb, lib/mini_magick/image/info.rb
* https://jira.lib.unc.edu/browse/HYC-618
=> Hyc 618 missing thumbnails

app/views/hyrax/base/show.html.erb, app/views/hyrax/file_sets/media_display/_image.html.erb, public/universalviewer/dist/uv-2.0.1/lib/uv-seadragon-extension.en-GB.config.json
Hide metadata panel. Same metadata shows below the image anyway.
Hide settings button
Remove download option from viewer. Add download link below viewer.
https://jira.lib.unc.edu/browse/HYC-647
https://jira.lib.unc.edu/browse/HYC-640
=> Uv viewer settings

app/assets/stylesheets/unc_custom.css.scss, app/views/_controls.html.erb, app/views/_masthead.html.erb, app/views/hyrax/homepage/_home_content.html.erb, app/views/hyrax/homepage/_unc_deposit.html.erb
=> Fix homepage margins on large screens

app/controllers/catalog_controller.rb, app/models/adminset_set.rb, app/models/language_set.rb, app/models/solr_document.rb, lib/tasks/test_data_import.rake, lib/tasks/test_setup.rake, spec/features/edit_work_spec.rb, spec/features/set_embargo_spec.rb, spec/requests/oai_pmh_endpoint_spec.rb, spec/tasks/migrate_rake_spec.rb, spec/tasks/proquest_ingest_rake_spec.rb
* https://jira.lib.unc.edu/browse/HYC-597
=> Hyc 597 oai admin sets

lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/metadata_parser.rb
* expired embargo visibility
* updated log statements to include record counter
* ensure files always have titles
=> Migration updates 04292019

config/authorities/departments.yml
* this does not include remediation
=> allied health affiliations

app/views/hyrax/base/_show_actions.html.erb
https://jira.lib.unc.edu/browse/HYC-644
=> Need dept name passed along in the url

config/authorities/departments.yml
https://jira.lib.unc.edu/browse/HYC-728
=> Update saved terms for art sub-depts.

lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/metadata_parser.rb
* Assume inheritance enabled unless overriden.
* If a parent work is private, then assume the child is private. 
* Pending review implies private
=> HYC-719 - Fixes to permissions inheritance

app/models/concerns/blacklight/document/dublin_core.rb
https://jira.lib.unc.edu/browse/HYC-722
=> HYC-722 - Add identifier linking to hyc record in OAI

app/controllers/catalog_controller.rb
https://jira.lib.unc.edu/browse/HYC-721
=> HYC-721 - Add real OAI config

app/forms/hyrax/artwork_form.rb, app/models/artwork.rb, app/presenters/hyrax/artwork_presenter.rb, app/views/hyrax/artworks/_attribute_rows.html.erb, spec/features/create_artwork_spec.rb, spec/forms/hyrax/artwork_form_spec.rb, spec/models/artwork_spec.rb, spec/presenters/hyrax/artwork_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-741
=> Add note field to artwork form

config/authorities/departments.yml, lib/tasks/replace_affiliation.rake
Relates to https://jira.lib.unc.edu/browse/HYC-729
=> Fix MFA affiliations

app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/base/_form_permission.html.erb
https://jira.lib.unc.edu/browse/HYC-697
=> Add note text for public visibility option

app/controllers/catalog_controller.rb, app/search_builders/restricted_single_result_builder.rb, lib/blacklight_oai_provider/solr_document_wrapper.rb
https://jira.lib.unc.edu/browse/HYC-709
=> HYC-709 - Restrict access to GetRecord for private records

app/assets/stylesheets/unc_custom.css.scss
Small fixes to prevent forms div from being too wide and fix to not have banner note overflow its container
=> Homepage style fixes

app/controllers/catalog_controller.rb
* https://jira.lib.unc.edu/browse/HYC-755
=> Change name of oai list set to admin_set

app/indexers/hyc_indexer.rb, app/models/solr_document.rb
* https://jira.lib.unc.edu/browse/HYC-731
=> Add edtf formatted date issued for oai feed

app/views/hyrax/homepage/_featured_fields.html.erb
https://jira.lib.unc.edu/browse/HYC-759
=> Remove collection info from featured display

app/indexers/hyc_indexer.rb
* Remove date formatting from date_issued_edtf as all migrated and incoming dates are already in edtf format, but not all are in the yyyy-mm-dd format
=> Index user-entered date issued value in solr

app/renderers/hyrax/renderers/attribute_renderer.rb, config/schema_org.yml
https://jira.lib.unc.edu/browse/HYC-758
=> Fix issues with schema.org metadata not displaying

app/services/proquest_department_mappings_service.rb, config/authorities/proquest_departments.yml, lib/tasks/proquest_ingest.rake, spec/fixtures/authorities/proquest_departments.yml, spec/fixtures/proquest/proquest_config.yml, spec/services/proquest_department_mappings_service_spec.rb, spec/tasks/proquest_ingest_rake_spec.rb
* https://jira.lib.unc.edu/browse/HYC-766
=> proquest ingest

app/controllers/application_controller.rb, app/helpers/hyrax_helper.rb, app/models/file_download_stat.rb, app/models/hyrax/download.rb, app/models/hyrax/statistic.rb
* https://jira.lib.unc.edu/browse/HYC-762
=> Hyc 762 ga combined stats

app/assets/javascripts/person_objects.js
https://jira.lib.unc.edu/browse/HYC-782
=> Update index for optional people fields

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.css, app/controllers/catalog_controller.rb, app/controllers/search_history_controller.rb, app/helpers/blacklight/facets_helper_behavior.rb, app/indexers/hyc/edtf_year_indexer.rb, app/indexers/hyc_indexer.rb, app/models/article.rb, app/models/artwork.rb, app/models/data_set.rb, app/models/dissertation.rb, app/models/general.rb, app/models/honors_thesis.rb, app/models/journal.rb, app/models/masters_paper.rb, app/models/multimed.rb, app/models/range_limit_catalog_search_builder.rb, app/models/scholarly_work.rb, app/models/search_builder.rb, config/routes.rb, lib/active_fedora/rdf/indexing_service.rb, spec/indexers/hyc/edtf_year_indexer_spec.rb
https://jira.lib.unc.edu/browse/HYC-634
=> Add slider to select year facet

app/assets/stylesheets/unc_custom.css.scss
https://jira.lib.unc.edu/browse/HYC-780
=> Style masonary view

lib/tasks/proquest_ingest.rake
* https://jira.lib.unc.edu/browse/HYC-784
=> Hyc 784 delete proquest zip

lib/tasks/migrate/services/ingest_service.rb, lib/tasks/migrate/services/metadata_parser.rb, lib/tasks/proquest_ingest.rake, spec/tasks/migrate_rake_spec.rb
* https://jira.lib.unc.edu/browse/HYC-772
=> Add group permissions to ingest rake tasks

app/helpers/hyc/doi_create.rb, lib/tasks/add_dois.rake
https://jira.lib.unc.edu/browse/HYC-776
Depends on: https://gitlab.lib.unc.edu/cdr/vagrant-rails/merge_requests/76
=> Create script to generate DOIs

app/controllers/catalog_controller.rb
https://jira.lib.unc.edu/browse/HYC-796
=> Reorder facets

app/forms/hyrax/artwork_form.rb, app/models/artwork.rb, app/presenters/hyrax/artwork_presenter.rb, spec/features/create_artwork_spec.rb, spec/forms/hyrax/artwork_form_spec.rb, spec/models/artwork_spec.rb, spec/presenters/hyrax/artwork_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-809
=> Add dcmi_type to artworks

app/forms/hyrax/general_form.rb, app/forms/hyrax/scholarly_work_form.rb, spec/features/create_general_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/forms/hyrax/general_form_spec.rb, spec/forms/hyrax/scholarly_work_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-805
=> Update DCMI types

lib/tasks/proquest_ingest.rake, spec/tasks/proquest_ingest_rake_spec.rb
* https://jira.lib.unc.edu/browse/HYC-811
=> Hyc 811 proquest metadata updates

app/models/concerns/hydra/role_management/user_roles.rb, app/presenters/hyrax/workflow_presenter.rb, app/views/hyrax/base/_show_actions.html.erb, spec/presenters/hyrax/workflow_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-807
=> Attach artwork button

app/services/dcmi_type_service.rb, app/views/records/edit_fields/_dcmi_type.html.erb, config/authorities/dcmi_types.yml, spec/features/create_article_spec.rb, spec/features/create_artwork_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_dissertation_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_multimed_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/fixtures/authorities/dcmi_types.yml, spec/forms/hyrax/article_form_spec.rb, spec/forms/hyrax/artwork_form_spec.rb, spec/forms/hyrax/data_set_form_spec.rb, spec/forms/hyrax/dissertation_form_spec.rb, spec/forms/hyrax/general_form_spec.rb, spec/forms/hyrax/honors_thesis_form_spec.rb, spec/forms/hyrax/journal_form_spec.rb, spec/forms/hyrax/masters_paper_form_spec.rb, spec/forms/hyrax/multimed_form_spec.rb, spec/forms/hyrax/scholarly_work_form_spec.rb, spec/services/dcmi_types_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-803
=> Make DCMI type a service

lib/tasks/proquest_ingest.rake
* updating fileset title
* adding supplemental files (whoops)
=> Even more proquest ingest updates

app/assets/javascripts/application.js
* https://jira.lib.unc.edu/browse/HYC-810
=> Include range search js after hyrax js without duplicate jquery-flot js

app/views/hyrax/dashboard/sidebar/_activity.html.erb, config/locales/hyrax.en.yml
* https://jira.lib.unc.edu/browse/HYC-806
=> Add link to sidekiq in admin dashboard

config/authorities/departments.yml
* https://jira.lib.unc.edu/browse/HYC-813
=> Update department vocab for onescience

spec/services/hyrax/workflow/deletion_approval_notification_spec.rb, spec/services/hyrax/workflow/deletion_request_rejection_notification_spec.rb, spec/services/hyrax/workflow/deposited_manager_notification_spec.rb, spec/services/hyrax/workflow/pending_deletion_notification_spec.rb, spec/services/hyrax/workflow/virus_found_notification_spec.rb
* https://jira.lib.unc.edu/browse/HYC-820
=> Update user and work attributes for email tests

app/services/degrees_service.rb, config/authorities/degrees.yml, spec/fixtures/authorities/degrees.yml, spec/services/degrees_service_spec.rb
* https://jira.lib.unc.edu/browse/HYC-815
=> update dissertation degrees

config/routes.rb, spec/features/redirect_doi_url_spec.rb
* https://jira.lib.unc.edu/browse/HYC-862
=> Redirect dois to correct pages

.travis.yml, app/helpers/hyc/doi_create.rb, spec/helpers/hyc/doi_create_spec.rb
* https://jira.lib.unc.edu/browse/HYC-840
* https://jira.lib.unc.edu/browse/HYC-841
=> Hyc 840 update doi minting

app/presenters/hyrax/stats_usage_presenter.rb, spec/presenters/hyrax/stats_usage_presenter_spec.rb
* https://jira.lib.unc.edu/browse/HYC-872
=> Update method for determining google analytics start date

app/services/tasks/update_doi_urls_service.rb, spec/services/tasks/update_doi_urls_service_spec.rb
* ensure retry number is an integer
=> Doi update service

app/services/tasks/update_doi_urls_service.rb, spec/services/tasks/update_doi_urls_service_spec.rb
* https://jira.lib.unc.edu/browse/HYC-878
=> doi update validation

lib/tasks/migration_helper.rb, spec/helpers/migration_helper_spec.rb, spec/spec_helper.rb
* https://jira.lib.unc.edu/browse/HYC-871
=> add viewer groups to migrated works

app/helpers/hyrax_helper.rb, app/lib/status_list_service_helper.rb, spec/fixtures/redirect_uuids.csv, spec/helpers/blacklight/facets_helper_behavior_spec.rb, spec/helpers/hyrax/citations_behaviors/formatters/apa_formatter_spec.rb, spec/helpers/hyrax/citations_behaviors/formatters/chicago_formatter_spec.rb, spec/helpers/hyrax/citations_behaviors/formatters/ml_formatter_spec.rb, spec/helpers/hyrax_helper_spec.rb
* https://jira.lib.unc.edu/browse/HYC-871
=> Hyc 852 helper tests

config/authorities/departments.yml, config/authorities/masters_papers_depts.yml
* https://jira.lib.unc.edu/browse/HYC-885
=> Rename school of media and journalism and add to masters paper dept list

app/assets/stylesheets/unc_custom.css.scss
=> Fix spacing of featured titles so they don't overlap with their header

public/robots.txt
* https://jira.lib.unc.edu/browse/HYC-883
=> Allow google scholar to crawl the site and include link to the sitemap in robots.txt

app/renderers/hyrax/renderers/attribute_renderer.rb, app/renderers/hyrax/renderers/person_attribute_renderer.rb
https://jira.lib.unc.edu/browse/HYC-884
=> Turn ORCID urls into links

app/controllers/catalog_controller.rb, app/indexers/hyc_indexer.rb
https://jira.lib.unc.edu/browse/HYC-808
Will require a full solr reindex
=> Add sort fields for title and date issued

config/initializers/hyrax.rb
https://jira.lib.unc.edu/browse/HYC-906.
Cloud files button was still showing up, so explicitly disabled in hyrax config.
=> Set Browse Everything to nil so Cloud Providers button doesn't display

app/controllers/catalog_controller.rb
https://jira.lib.unc.edu/browse/HYC-925
=> Update sort labels

app/assets/javascripts/unc/unc_visibility_component.es6, app/assets/stylesheets/unc_custom.css.scss
https://jira.lib.unc.edu/browse/HYC-801
=> Don't show disabled visibility settings to non-admins

app/assets/javascripts/unc/unc_custom.js, app/assets/stylesheets/unc_custom.css.scss
https://jira.lib.unc.edu/browse/HYC-920
Supersedes https://github.com/UNC-Libraries/hy-c/pull/480, which had weird spacing on record view page that was unrelated to the pull request.
=> Selectively display "Remove" button for based_near field values

app/services/languages_service.rb, app/services/tasks/proquest_ingest_service.rb, lib/tasks/migration_helper.rb, spec/fixtures/proquest/proquest_config.yml, spec/helpers/migration_helper_spec.rb, spec/services/tasks/proquest_ingest_service_spec.rb
* https://jira.lib.unc.edu/browse/HYC-912
* https://gitlab.lib.unc.edu/cdr/hyc-utils/merge_requests/16
=> Hyc 912 proquest ingest workflow

spec/indexers/hyc_indexer_test.rb, spec/indexers/hyrax/deep_indexing_service_test.rb
* https://jira.lib.unc.edu/browse/HYC-853
=> Hyc 853 indexer tests

app/services/tasks/doi_create_service.rb
https://jira.lib.unc.edu/browse/HYC-928
=> Add timestamp to doi creation log statements

app/views/shared/_citations.html.erb
* https://jira.lib.unc.edu/browse/HYC-882
=> Add google scholar tags for journal metadata

config/authorities/degrees.yml
https://jira.lib.unc.edu/browse/HYC-935
=> Add pharmacy to honors thesis list

app/services/tasks/onescience_ingest_service.rb
* https://jira.lib.unc.edu/browse/HYC-961
* handle multiple scopus xml files at once
* remove nil values from people objects
=> HYC-961 Update onescience script to fix affiliations

app/controllers/catalog_controller.rb, app/models/adminset_set.rb, app/models/cdr_list_set.rb, app/models/solr_document.rb, spec/requests/oai_pmh_endpoint_spec.rb
* https://jira.lib.unc.edu/browse/HYC-1011
=> Add collections as a facet for oai list sets

config/authorities/degrees.yml
https://jira.lib.unc.edu/browse/HYC-1022
=> Add digital communications to masters list

app/jobs/bulkrax/import_work_job.rb, spec/jobs/bulkrax/import_work_job_spec.rb
* https://jira.lib.unc.edu/browse/HYC-1018
=> bulkrax statuses

app/lib/hydra/derivatives/processors/document.rb, app/lib/hydra/derivatives/processors/image.rb
* https://jira.lib.unc.edu/browse/HYC-980
=> inverted thumbnails

app/views/layouts/_head_tag_content.html.erb
* https://jira.lib.unc.edu/browse/HYC-1039
=> Add noindex meta tag to work show page for specified works

app/services/tasks/proquest_ingest_service.rb
* https://jira.lib.unc.edu/browse/HYC-1025
=> Update proquest resource type

config/initializers/bulkrax.rb
* https://jira.lib.unc.edu/browse/HYC-1034
=> Update the location of bulkrax uploads

app/jobs/bulkrax/importer_job.rb
* https://jira.lib.unc.edu/browse/HYC-1035
=> Hyc 1035 bulkrax corrected entries

app/views/catalog/_facet_pagination.html.erb
* https://jira.lib.unc.edu/browse/HYC-1040
=> Remove visible span tags

app/models/concerns/blacklight/document/dublin_core.rb
* https://jira.lib.unc.edu/browse/HYC-1047
=> Remove index prefix from names in oai feed

app/assets/javascripts/unc/unc_custom.js, app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/base/_citations.html.erb
https://jira.lib.unc.edu/browse/BXC-2743
=> Add link to request accessible copy of a file

app/models/concerns/bulkrax/has_matchers.rb
* https://jira.lib.unc.edu/browse/HYC-1051
=> Parse multi-valued fields from bulkrax csv file

app/models/concerns/bulkrax/has_local_processing.rb
* https://jira.lib.unc.edu/browse/HYC-1054
=> Add label fields for bulkrax imports

config/authorities/departments.yml
https://jira.lib.unc.edu/browse/HYC-1062
=> Add RLA to department list

Gemfile, Gemfile.lock, app/models/bulkrax/csv_entry.rb, app/parsers/bulkrax/csv_parser.rb
* https://jira.lib.unc.edu/browse/HYC-1056
=> bulkrax error handling

app/services/hyrax/workflow/honors_department_reviewer_deposit_notification.rb, app/services/hyrax/workflow/honors_mediated_deposit_notification.rb, config/locales/hyrax.en.yml, config/workflows/honors_thesis_deposit_workflow.json, spec/features/create_work_in_honors_thesis_workflow_spec.rb, spec/services/hyrax/workflow/honors_department_reviewer_deposit_notification_spec.rb, spec/services/hyrax/workflow/honors_mediated_deposit_notification_spec.rb
* https://jira.lib.unc.edu/browse/HYC-779
=> Add custom emails for depositors and department contacts in the honors thesis workflow

lib/qa/authorities/geonames.rb
Bump up geonames returned results, as it has difficulties finding just "North Carolina" in the first 10 results.
https://jira.lib.unc.edu/browse/HYC-1057
=> Bump up geonames returned results size

app/controllers/catalog_controller.rb
https://jira.lib.unc.edu/browse/HYC-1009
=> Date issued sort fix

app/parsers/bulkrax/csv_parser.rb
* https://jira.lib.unc.edu/browse/HYC-1060
* also will open PR in gem
=> Use number of records as row limit in solr queries

app/matchers/bulkrax/application_matcher.rb, spec/matchers/bulkrax/application_matcher_spec.rb
* https://jira.lib.unc.edu/browse/HYC-1066
=> bulkrax parsing

app/assets/stylesheets/unc_custom.css.scss
https://jira.lib.unc.edu/browse/HYC-836
=> Position inner toolbar

app/views/hyrax/collections/_show_descriptions.html.erb, app/views/hyrax/dashboard/collections/_show_descriptions.html.erb
https://jira.lib.unc.edu/browse/HYC-666
=> Display collection language as human readable link

app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/file_sets/media_display/_audio.html.erb, app/views/hyrax/file_sets/media_display/_default.html.erb, app/views/hyrax/file_sets/media_display/_image.html.erb, app/views/hyrax/file_sets/media_display/_office_document.html.erb, app/views/hyrax/file_sets/media_display/_pdf.html.erb, app/views/hyrax/file_sets/media_display/_video.html.erb
https://jira.lib.unc.edu/browse/HYC-1072
=> Make download button more visible

app/models/user.rb
* https://jira.lib.unc.edu/browse/HYC-1065
=> update user model to require uid to be unique and not blank

app/presenters/hyrax/work_show_presenter.rb
https://jira.lib.unc.edu/browse/HYC-1074
=> Make sure person name is returned instead of index

app/actors/hyrax/actors/base_actor.rb
* https://jira.lib.unc.edu/browse/HYC-992
=> Add methods to base actor to apply work-specific workflow permissions

app/services/tasks/onescience_ingest_service.rb, lib/tasks/onescience/onescience_ingest.rake, spec/fixtures/onescience/onescience_config.yml, spec/fixtures/onescience/scoups_departments-mapped.csv, spec/services/tasks/onescience_ingest_service_spec.rb
* https://jira.lib.unc.edu/browse/HYC-1063
=> Hyc 1063 1science script updates

app/services/tasks/proquest_ingest_service.rb, spec/services/tasks/proquest_ingest_service_spec.rb
* https://jira.lib.unc.edu/browse/HYC-1053
=> Add rights_statement_label to proquest ingest script

app/services/tasks/onescience_ingest_service.rb
do not add record id to progress log
=> Skip to next record if there are no files

app/assets/stylesheets/unc_custom.css.scss
=> Multiple ids with same name. So, use default styling if download is in a drop down

app/views/roles/edit.html.erb
https://jira.lib.unc.edu/browse/HYC-1080
=> Display add user link as a button

app/forms/hyrax/scholarly_work_form.rb, spec/forms/hyrax/scholarly_work_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-1107
=> Add identifier field

config/authorities/departments.yml
https://jira.lib.unc.edu/browse/HYC-1112
=> Add dental hygiene undergrad program

app/forms/hyrax/journal_form.rb, spec/forms/hyrax/journal_form_spec.rb
https://jira.lib.unc.edu/browse/HYC-1124
=> Admin note error fix

app/models/concerns/blacklight/document/dublin_core.rb
https://jira.lib.unc.edu/browse/HYC-1108
=> Add file download link to oai feed

config/environments/production.rb
https://jira.lib.unc.edu/browse/HYC-1136
=> Tone down the log messages

config/authorities/masters_papers_depts.yml
https://jira.lib.unc.edu/browse/HYC-1137
=> Add new departments

app/controllers/concerns/hyrax/controller.rb, app/services/departments_service.rb, app/services/languages_service.rb, config/application.rb, config/initializers/riiif.rb
https://jira.lib.unc.edu/browse/HYC-1125
https://jira.lib.unc.edu/browse/HYC-1126
https://jira.lib.unc.edu/browse/HYC-1128
https://jira.lib.unc.edu/browse/HYC-1132
=> Address log spam

config/authorities/masters_papers_depts.yml
https://jira.lib.unc.edu/browse/HYC-1144
=> Add biostats to masters papers list

app/inputs/multi_value_input.rb, app/services/tasks/onescience_ingest_service.rb
https://jira.lib.unc.edu/browse/HYC-1122
https://jira.lib.unc.edu/browse/HYC-1141
=> Only convert input field dates to edtf

app/controllers/errors_controller.rb, config/routes.rb
https://jira.lib.unc.edu/browse/HYC-1129
=> Fix 404 not found template error

app/models/hyrax/statistic.rb
https://jira.lib.unc.edu/browse/HYC-1134
=> Catch GA stats retrieval timeout errors and return cached stats

app/jobs/assign_permissions_to_work_job.rb
https://jira.lib.unc.edu/browse/HYC-1131
=> Check users exist before assigning email recipients

app/controllers/application_controller.rb, app/controllers/hyrax/downloads_controller.rb
https://jira.lib.unc.edu/browse/HYC-1133
=> Blacklight record not found error

app/services/tasks/onescience_ingest_service.rb
https://jira.lib.unc.edu/browse/HYC-1146
=> Allow multiple metadata spreadsheets

app/services/tasks/onescience_ingest_service.rb
https://jira.lib.unc.edu/browse/HYC-1146
=> Add each metadata file separately

app/forms/hyrax/data_set_form.rb, app/forms/hyrax/scholarly_work_form.rb, app/models/data_set.rb, app/models/scholarly_work.rb, app/presenters/hyrax/data_set_presenter.rb, app/presenters/hyrax/scholarly_work_presenter.rb, app/views/hyrax/data_sets/_attribute_rows.html.erb, app/views/hyrax/scholarly_works/_attribute_rows.html.erb, spec/forms/hyrax/data_set_form_spec.rb, spec/forms/hyrax/scholarly_work_form_spec.rb, spec/models/data_set_spec.rb, spec/models/scholarly_work_spec.rb, spec/presenters/hyrax/data_set_presenter_spec.rb, spec/presenters/hyrax/scholarly_work_presenter_spec.rb
https://jira.lib.unc.edu/browse/HYC-1154
=> Add note field to Datasets and Scholarly Works

app/services/tasks/onescience_ingest_service.rb
* Revert multi-file changes
* Make sure more fields are strings
https://jira.lib.unc.edu/browse/HYC-1146
=> Revert multi-file changes

app/services/tasks/onescience_ingest_service.rb
* Make sure more fields are strings
* Revert multi-file changes
=> Reset onescience ingest script

app/indexers/hyrax/collection_indexer.rb, app/views/records/edit_fields/_date_created.html.erb
https://jira.lib.unc.edu/browse/HYC-1187
=> Collection sorting

app/controllers/application_controller.rb
https://jira.lib.unc.edu/browse/HYC-1168
=> Catch various routing and request errors

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/assets/stylesheets/unc_custom.css.scss, app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/helpers/range_limit_helper.rb
https://jira.lib.unc.edu/browse/HYC-1160
https://jira.lib.unc.edu/browse/HYC-1167
Depends on https://gitlab.lib.unc.edu/cdr/hyc-gems/-/merge_requests/64
=> Catch blacklight sort and number formatting errors

app/controllers/application_controller.rb
https://jira.lib.unc.edu/browse/HYC-1164
=> Return json for imageNotFoundError

app/controllers/application_controller.rb
https://jira.lib.unc.edu/browse/HYC-1165
=> Catch Invalid Authenticity Token errors

app/controllers/application_controller.rb, app/controllers/concerns/hydra/controller/download_behavior.rb
* Fix 404 error path
* Catch ObjectNotFound error from fedora
https://jira.lib.unc.edu/browse/HYC-1207
https://jira.lib.unc.edu/browse/HYC-1162
=> Fix 404 error path

app/actors/hyrax/actors/base_actor.rb
https://jira.lib.unc.edu/browse/HYC-1212
=> HYC-1212 - Prevent attempts to add duplicate sipity entity

app/lib/bulkrax.rb, config/initializers/bulkrax.rb
https://jira.lib.unc.edu/browse/HYC-1214
=> Update import/export paths for bulkrax

Gemfile.lock
https://jira.lib.unc.edu/browse/BXC-3265
Depends on https://gitlab.lib.unc.edu/cdr/hyc-gems/-/merge_requests/72
=> Bump version of dry validation to fix deprecation notice in script output

app/models/concerns/bulkrax/file_factory.rb, app/parsers/bulkrax/csv_parser.rb
https://jira.lib.unc.edu/browse/HYC-1220
=> Bulkrax import/export issues

.github/workflows/build.yml, README.md
* Verify that tests are passing on commits / merges to main (should almost always be the same as PR, but every once in a while they're not)
* Have badge reflect status of main branch, rather than last workflow run
=> Run tests on commits to main, display badge for main

app/models/concerns/bulkrax/file_factory.rb, spec/models/bulkrax/concerns/file_factory.rb
- https://jira.lib.unc.edu/browse/HYC-1229
- https://jira.lib.unc.edu/browse/HYC-1268
=> Don't hardcode file name and mime type if replacing a file

config/authorities/licenses.yml
Connected to: https://jira.lib.unc.edu/browse/HYC-1279
=> Add license to allow for Sage ingest

app/assets/stylesheets/unc_custom.css.scss, app/views/shared/_footer.html.erb, config/initializers/git_sha.rb, spec/features/footer_spec.rb
Connected to https://jira.lib.unc.edu/browse/HYC-1264 
- Styling to maintain look and feel
- Set constants in an initializer (the pattern that DCE has used - makes it harder to test production-only code, though)
CDR footer on production in v1.0.0:
Deployed to cdr-test  - mobile
Deployed to cdr-test - desktop
=> Add version footer

.gitignore, db/schema.rb
Connected to https://jira.lib.unc.edu/browse/HYC-1306
- This will allow us to run rake db:setup on new environments and in testing, rather than rake db:migrate, which can take significantly longer and occasionally lead to unexpected results. (db:migrate is intended for existing systems that need to be updated)
=> Commit schema to git

app/search_builders/range_limit_catalog_search_builder.rb, spec/features/full_text_search_spec.rb, spec/search_builders/range_limit_catalog_search_builder_spec.rb
Connected to https://jira.lib.unc.edu/browse/HYC-1304 
Previous PR introduced different bug (see comments on ticket)
=> HYC-1304: Fix syntax for join query in Solr

app/models/jats_ingest_work.rb, app/services/tasks/sage_ingest_service.rb, spec/features/edit_sage_ingested_works_spec.rb, spec/models/jats_ingest_work_spec.rb, spec/services/tasks/sage_ingest_service_spec.rb
Requests per Rebekah 
- make Articles public / open from creation
- add https://doi.org to number-only dois
=> HYC-1280: Update visibility and doi URI

app/services/tasks/sage_ingest_service.rb, spec/factories/admin_sets.rb, spec/factories/permission_templates.rb, spec/factories/workflow_actions.rb, spec/factories/workflow_states.rb, spec/factories/workflows.rb, spec/features/edit_sage_ingested_works_spec.rb, spec/fixtures/sage/sage_config.yml, spec/services/tasks/sage_ingest_service_spec.rb
- Factories borrowed from Hyrax factories of the same names
- Sipity makes me very unhappy
Deployed to cdr-test, rake task run on https://cdr-test.lib.unc.edu/catalog?f%5Badmin_set_sim%5D%5B%5D=Sage+test+five+admin+set&locale=en - they appear to have workflows!
=> HYC-1282: Add Sage Articles to workflow

app/services/version_service.rb, config/initializers/git_sha.rb, spec/services/version_service_spec.rb
- Makes version information more testable
- Avoids errors using mutagen with Docker
=> Add a version service

docker-compose.yml
...while we find a more permanent home.
Two tests to confirm that this is working:
1)`docker compose pull` will try to pull from the repo under my account.
2) `docker compose build; docker compose push` will rebuild the containers and push them to the repo under my account. You will need to login with `docker login` first. @bbpennel @lfarrell @sharonluong should all have access.
=> Migrate docker repo to @cazzerson on Docker Hub

config/authorities/departments.yml
https://jira.lib.unc.edu/browse/HYC-1449
=> Add earth sciences department

.github/workflows/build.yml, app/lib/mini_magick/image/info.rb, app/services/image_service.rb, spec/lib/hydra/derivatives/processors/image.rb, spec/services/image_service_spec.rb, spec/support/image_source_data.rb
[https://jira.lib.unc.edu/browse/HYC-1438](https://jira.lib.unc.edu/browse/HYC-1438)
Remove ImageMagick and simplify code
=> Hyc 1438 only graphicsmagick

app/models/solr_document.rb, lib/active_fedora/rdf/indexing_service.rb
https://jira.lib.unc.edu/browse/HYC-1475
* Index contributor_label_tesim, which is needed for the advanced search page
=> HYC-1475 - Index contributor label field

.rubocop_todo.yml, app/controllers/catalog_controller.rb, solr/new_config/schema.xml
https://jira.lib.unc.edu/browse/HYC-1476
=> Allow searching by rights statement text

app/models/jats_ingest_work.rb, spec/fixtures/sage/10.1177_08901171221077812.xml, spec/models/jats_ingest_work_spec.rb
https://jira.lib.unc.edu/browse/HYC-1471
=> Check that kwd-group isn't nil for Sage ingests

app/overrides/models/file_download_stat_override.rb, app/overrides/models/hyrax/statistic_override.rb, spec/models/file_download_stat_spec.rb, spec/models/hyrax/statistic_spec.rb
* Adjustments to the way overrides work for two statistics classes to reduce the amount of upstream code we are duplicating. Improvement, or not?
=> Sandi overrides

app/lib/status_list_service_helper.rb
https://jira.lib.unc.edu/browse/HYC-1492
* Add a note about why we are not adding test coverage for this class, will create a followup ticket for addressing the override.
=> HYC-1492 - StatusListService fixme comment

app/presenters/hyrax/workflow_presenter.rb, app/views/hyrax/base/_show_actions.html.erb, app/views/hyrax/base/show.html.erb, db/migrate/20221012131643_update_single_use_links_column_names.hyrax.rb, db/migrate/20221012131644_change_sipity_entity_specific_responsibility.hyrax.rb, db/migrate/20221012131645_create_default_administrative_set.hyrax.rb, spec/features/create_artwork_spec.rb
https://jira.lib.unc.edu/browse/HYC-1554
* Updates related view files to match the changes from hyrax 3
* Updates workflow presenter
* Adds cleaning to one of the tests that was failing due to the work action buttons not showing, so that the test full passes.
* Fix rubocop issues in migration files
=> HYC-1554 - Get work page action buttons showing again

app/overrides/inputs/multi_value_input_override.rb
Part of https://jira.lib.unc.edu/browse/HYC-1198
* Switches it to an override and reduces amount of code (some of which changed since the file was originally overridden)
=> HYC-1198 - Update MultiValueInput override

app/overrides/forms/collection_form_override.rb, spec/forms/hyrax/collection_form_spec.rb
Part of https://jira.lib.unc.edu/browse/HYC-1198
=> HYC-1198 - Add alternative_title to collection form from hyrax 3

app/overrides/actors/hyrax/actors/base_actor_override.rb
Part of https://jira.lib.unc.edu/browse/HYC-1198
=> HYC-1198 - Update base_actor_override.rb based off hyrax 3

app/views/_controls.html.erb, app/views/_masthead.html.erb, app/views/hyrax/admin/admin_sets/_show_document_list_row.html.erb, app/views/hyrax/base/_form_child_work_relationships.html.erb, app/views/hyrax/base/_form_member_of_collections.html.erb, app/views/hyrax/base/_form_permission.html.erb, app/views/hyrax/base/_form_progress.html.erb, app/views/hyrax/base/_form_relationships.html.erb, app/views/hyrax/base/_form_visibility_component.html.erb, app/views/hyrax/base/_guts4form.html.erb, app/views/hyrax/base/_items.html.erb, app/views/hyrax/base/_member.html.erb, app/views/hyrax/base/_metadata.html.erb, app/views/hyrax/base/_relationships.html.erb, app/views/hyrax/collections/_show_descriptions.html.erb
* First batch of smallish view updates, and a few deletions
=> HYC-1198 - Hyrax 3 view override updates, batch 1

app/controllers/concerns/hyrax/controller.rb
Part of https://jira.lib.unc.edu/browse/HYC-1198
* I was not able to switch this to an override, since it is a module and includes a `included` block, which cannot be duplicated/overridden. Removing the unmodified code also did not work.
=> HYC-1198 - Update Hyrax::Controller for hyrax 3

app/views/hyrax/base/_citations.html.erb
https://jira.lib.unc.edu/browse/HYC-1566
=> HYC-1566 - Update base/_citations.html.erb for hyrax 3

spec/controllers/hyrax/restricted_work_type_controller_spec.rb, spec/features/create_article_spec.rb, spec/features/create_artwork_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_dissertation_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_multimed_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/features/create_work_in_honors_thesis_workflow_spec.rb, spec/features/edit_work_spec.rb, spec/features/read_only_mode_spec.rb, spec/features/set_embargo_spec.rb
https://jira.lib.unc.edu/browse/HYC-1556
* Addresses save failure errors
* Fixes reference to add-file button that changed in hyrax 3
=> HYC-1556 - Fix some of the failures with create feature tests

spec/features/edit_sage_ingested_works_spec.rb
https://jira.lib.unc.edu/browse/HYC-1559
* Update selector for getting keyword values
=> HYC-1559 - Fix sage edit feature test

app/forms/hyrax/article_form.rb, app/forms/hyrax/artwork_form.rb, app/forms/hyrax/data_set_form.rb, app/forms/hyrax/dissertation_form.rb, app/forms/hyrax/general_form.rb, app/forms/hyrax/honors_thesis_form.rb, app/forms/hyrax/journal_form.rb, app/forms/hyrax/masters_paper_form.rb, app/forms/hyrax/multimed_form.rb, app/forms/hyrax/scholarly_work_form.rb, spec/features/create_article_spec.rb, spec/features/create_data_set_spec.rb, spec/features/create_dissertation_spec.rb, spec/features/create_general_spec.rb, spec/features/create_honors_thesis_spec.rb, spec/features/create_journal_spec.rb, spec/features/create_masters_paper_spec.rb, spec/features/create_multimed_spec.rb, spec/features/create_scholarly_work_spec.rb, spec/support/hyc_geoname_helper.rb
https://jira.lib.unc.edu/browse/HYC-1560
* Expands on https://github.com/UNC-Libraries/hy-c/pull/900 to fix geoname stubbing for all the tests referencing it
* Address HYC-1560 by removing duplicate fields from form (was causing most of the feature tests to fail)
=> HYC-1556/1560 - More fixes for work creation feature tests

spec/features/edit_batch_of_works_spec.rb
https://jira.lib.unc.edu/browse/HYC-1555
All tests in the files tagged in the ticket should now pass.
=> Fix missing depositor key

app/presenters/hyrax/general_presenter.rb, app/presenters/hyrax/honors_thesis_presenter.rb, app/presenters/hyrax/journal_presenter.rb, app/presenters/hyrax/masters_paper_presenter.rb, app/presenters/hyrax/scholarly_work_presenter.rb, spec/forms/hyrax/article_form_spec.rb, spec/forms/hyrax/artwork_form_spec.rb, spec/forms/hyrax/data_set_form_spec.rb, spec/forms/hyrax/dissertation_form_spec.rb, spec/forms/hyrax/general_form_spec.rb, spec/forms/hyrax/honors_thesis_form_spec.rb, spec/forms/hyrax/journal_form_spec.rb, spec/forms/hyrax/masters_paper_form_spec.rb, spec/forms/hyrax/multimed_form_spec.rb, spec/forms/hyrax/scholarly_work_form_spec.rb
added new fields from basic_metadata to the expectations on the form tests
https://jira.lib.unc.edu/browse/HYC-1552
=> HYC-1552 added new fields to test expectations

app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/base/show.html.erb
https://jira.lib.unc.edu/browse/HYC-1573
=> Hyrax 3 styling updates

.github/workflows/build.yml, Dockerfile
* Trigger update of rubygems in dockerfile to resolve issues finding bulkrax. Update gh actions version of rubygems
=> Hyrax-3 Update rubygems for docker

app/services/tasks/setup_tasks_service.rb, spec/features/boxc_redirect_spec.rb, spec/features/edit_sage_ingested_works_spec.rb, spec/services/proquest_department_mappings_service_spec.rb, spec/services/tasks/doi_create_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-1571
=> Address deprecations and warnings

config/authorities/departments.yml
Add new department to the department vocab
https://jira.lib.unc.edu/browse/HYC-1576
=> Add dept of health sciences

app/assets/stylesheets/unc_custom.css.scss
- https://jira.lib.unc.edu/browse/HYC-1579
- https://jira.lib.unc.edu/browse/HYC-1580
=> Fix layout of  work request buttons and download button color

app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/base/show.html.erb
https://jira.lib.unc.edu/browse/HYC-1580
=> Center citation and download buttons

config/authorities/departments.yml
https://jira.lib.unc.edu/browse/HYC-1588
=> Add African Studies Center to departments list

app/overrides/services/hyrax/solr_query_service_override.rb, spec/services/hyrax/workflow/notification_service_spec.rb
https://jira.lib.unc.edu/browse/HYC-1577
* Temporary fix for Review Submissions, which currently needs to return all results to the browser rather than paging server side
=> HYC-1577 - Fix Review Submissions page only returning 10 results

app/lib/mini_magick/image/info.rb
https://jira.lib.unc.edu/browse/HYC-1619
* Change how string is updated so it doesn't attempt to modify a frozen string.
=> HYC-1619 - Minimagick, Don't try to modify frozen string

app/views/bulkrax/importers/new.html.erb
https://jira.lib.unc.edu/browse/HYC-1621
* Removing the Create And Validate button since using it is disastrous
* Move around the previous override for clarity
=> HYC-1621 - Remove importer Create and Validate button

app/overrides/controllers/hyrax/stats_controller_override.rb, app/overrides/services/hyrax/analytics/google/events_daily_override.rb, spec/controllers/hyrax/stats_controller_spec.rb
https://jira.lib.unc.edu/browse/HYC-1636
* Override stats controller to retrieve and combine DownloadIR stats for the first 100 filesets in a work
=> HYC-1636 - Aggregate fileset DownloadIR stats for Work Downloads

app/overrides/services/hyrax/solr_query_service_override.rb
* Temporary change to page size to prevent review submissions page from consuming too much memory
=> Short term review submissions page load time fix

config/authorities/masters_papers_depts.yml
https://jira.lib.unc.edu/browse/HYC-1656
=> HYC-1656 - Add computer science to list of masters papers depts

app/views/_user_util_links.html.erb, app/views/shared/_footer.html.erb, config/locales/hyrax.en.yml
https://jira.lib.unc.edu/browse/HYC-1666
=> Add about link to header and footer

README.md
https://jira.lib.unc.edu/browse/HYC-1732
=> HYC-1732 - Add instructions for adding ingest from ftp admin sets

.rubocop_todo.yml, app/overrides/services/hyrax/workflow/pending_review_notification_override.rb, app/overrides/services/hyrax/workflow/workflow_action_service_override.rb, config/environments/development.rb, config/puma.rb, docker-compose.yml, docker/.env, docker/start-app.sh, docker/start-sidekiq.sh
https://unclibrary.atlassian.net/browse/HYC-1595
* Sidekiq run as its own docker container in dev environment
* Uses same base image as the web app container
* Has a new start script, which waits for the web app script to start and update gems, before running sidekiq
* Start scripts update rubygems-update so that listing of gems available will get updated after construction of base image
* Updates rails to allow the web application to be addressed as "web" in the dev environment, so that other contains can make requests to it. This is a new security restriction in rails 6.
Note: the tests will not pass in this PR
=> HYC-1595 - Sidekiq 6 in docker

config/authorities/departments.yml
https://unclibrary.atlassian.net/browse/HYC-1750
=> HYC-1750 - Update department names

app/models/concerns/blacklight/document/dublin_core.rb
https://unclibrary.atlassian.net/browse/HYC-1733
=> HYC-1733 - Remove mapping of affiliation to contributor

app/overrides/models/concerns/blacklight/document/dublin_core_override.rb, spec/models/concerns/blacklight/document/dublin_core_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1733
=> HYC-1733 - Remove mapping of affiliation to contributor - Hyrax 4

app/views/hyrax/base/_form_visibility_component.html.erb, app/views/hyrax/file_sets/media_display/_image.html.erb
* Add missing paren, remove extra closing tag
=> Hyrax-4 fix syntax errors

app/assets/stylesheets/unc_custom.css.scss, app/controllers/catalog_controller.rb, app/views/_controls.html.erb, app/views/catalog/_search_form.html.erb
Doesn't include issue 11 from the ticket, as I can't currently create any works to view what the file option dropdown looks like.
=> HYC-1752 - Hyrax 4 CSS updates

app/assets/stylesheets/unc_custom.css.scss
Issue #10 on [hyc-1752](https://unclibrary.atlassian.net/browse/HYC-1752)
=> Display file option buttons the same

app/views/ingest_from_ftp/list_packages.html.erb, app/views/ingest_from_ftp/view_status.html.erb, app/views/records/edit_fields/_person.html.erb
https://unclibrary.atlassian.net/browse/HYC-1773
* Updates views to work with bootstrap 4
* Replaces other usages of glyphicons with font awesome, since glyphicon was removed from bootstrap default
=> HYC-1728 - Update ingest from ftp, glyphicons

app/assets/stylesheets/unc_custom.css.scss, app/views/records/edit_fields/_person.html.erb
- https://unclibrary.atlassian.net/browse/HYC-1768
- https://unclibrary.atlassian.net/browse/HYC-1771
- https://unclibrary.atlassian.net/browse/HYC-1778
=> Various style updates for Bootstrap 4

app/views/hyrax/dashboard/sidebar/_custom_activity.html.erb, config/initializers/hyrax.rb
https://unclibrary.atlassian.net/browse/HYC-1776
* Add custom activity partial for menu to add back in sidekiq link
=> HYC-1776 - Sidekiq menu entry

app/assets/stylesheets/unc_custom.css.scss
https://unclibrary.atlassian.net/browse/HYC-1769
=> Fix spacing of buttons on admin set worktype page and clean up sidebar

app/assets/stylesheets/unc_custom.css.scss, app/views/_masthead.html.erb, app/views/layouts/hyrax.html.erb
https://unclibrary.atlassian.net/browse/HYC-1779
=> Fixes for the mobile menu

app/assets/stylesheets/unc_custom.css.scss
.
https://unclibrary.atlassian.net/browse/HYC-1785
=> Hide mobile facet toggler and add margin to the bottom of the facet list

app/views/default_admin_sets/_form.html.erb, app/views/default_admin_sets/edit.html.erb, app/views/default_admin_sets/index.html.erb, app/views/default_admin_sets/new.html.erb
https://unclibrary.atlassian.net/browse/HYC-1786
* Fix styling in the worktype assignment pages.
* Refactor header a little bit to cut down on duplication and get the title more consistent
=> HYC-1786 - Default worktype assignment style fixes (hyrax-4)

app/views/accounts/new.html.erb, app/views/masters_papers/department.html.erb
https://unclibrary.atlassian.net/browse/HYC-1789
https://unclibrary.atlassian.net/browse/HYC-1791
* Updates "add new master's paper" department selection page
* Updates "add new user" page styles
=> HYC- 1789/1791 - Masters paper and new user styles (hyrax-4)

app/controllers/catalog_controller.rb
https://unclibrary.atlassian.net/browse/HYC-1796
=> HYC-1796 - add worktype to set_fields

app/services/tasks/group_permission_remediation_service.rb
* If an error occurs while remediating an item, then log it and continue. 
* Log to a custom log instead of the production log
=> HYC-1781 - Remediation script error handling/logging

app/controllers/catalog_controller.rb
https://unclibrary.atlassian.net/browse/HYC-1817
* Switch to creator_label_tesim since we don't index creator_tesim
=> HYC-1817 - Search my works by creator

config/initializers/devise.rb
https://unclibrary.atlassian.net/browse/HYC-1819
Use env variable for devise key, falling back to secret key base if not set
=> HYC-1819 - Devise var

Gemfile, Gemfile.lock
https://unclibrary.atlassian.net/browse/HYC-1829
=> HYC-1829 - Hyrax update to fix adding files to existing works

config/locales/hyrax.en.yml, config/locales/scholarly_work.en.yml, spec/features/create_scholarly_work_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1804
adjusted yaml files and tests to include research protocol for scholarly works
=> HYC-1804 - Research Protocol modification for "Other Deposits" modal

config/authorities/resource_types.yml
https://unclibrary.atlassian.net/browse/HYC-1803
research protocol added to resource_types.yml
=> HYC-1803 -Research Protocol in resource_types.yml

app/services/tasks/doi_create_service.rb
https://unclibrary.atlassian.net/browse/HYC-1806
new research protocol mapping
=> HYC-1806 - Research Protocol in Datacite Mapping

app/assets/stylesheets/unc_custom.css.scss
https://unclibrary.atlassian.net/browse/HYC-1824
=> Fixes pagination links displaying vertically.

Gemfile, Gemfile.lock, docker/start-app.sh, docker/start-sidekiq.sh
* changing rubygems-update version to prevent resolution to 3.5
* updating gemfile
* pairs with PR for hyrax (https://github.com/UNC-Libraries/hyrax/pull/3)
=> HYC 1854 - Gemfile and Rubygems Modifications

app/views/catalog/_thumbnail_list_collection.html.erb, app/views/catalog/_thumbnail_list_default.html.erb, app/views/hyrax/admin/admin_sets/_show_document_list_row.html.erb, app/views/hyrax/admin/admin_sets/show.html.erb, app/views/hyrax/base/_file_manager_thumbnail.html.erb, app/views/hyrax/collections/_list_works.html.erb, app/views/hyrax/dashboard/collections/_list_works.html.erb
https://unclibrary.atlassian.net/browse/HYC-1856
=> Add alt text to thumbnails

app/views/catalog/_search_form.html.erb
https://unclibrary.atlassian.net/browse/HYC-1865
=> Check search state before trying to convert it

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1863
* Replace the blacklight filter field 'f' with a Parameters object if it has an invalid value in it, like a string. 
* Update blacklight version
=> HYC-1863 - Prevent invalid filter field values

Gemfile, Gemfile.lock
https://unclibrary.atlassian.net/browse/HYC-1866
Depends on https://github.com/UNC-Libraries/hyrax/pull/4 being merged
=> HYC-1866 - Prompt user to log in for /dashboard/collections

app/overrides/controllers/hydra/controller/download_behavior_override.rb, spec/controllers/hyrax/downloads_controller_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1877
* Assume client wants whole file if requesting a range but not specifying any bytes
=> HYC-1877 - Handle empty byte Range 

app/assets/stylesheets/unc_custom.css.scss, app/views/hyrax/base/_social_media.html.erb
https://unclibrary.atlassian.net/browse/HYC-1857
=> Update twitter icon

config/initializers/routing_error_logger_defatalizer.rb
https://unclibrary.atlassian.net/browse/HYC-1893
* Defatalize all the errors that we're handling in application controller.
* Refactor it to use a set of error classes
=> HYC-1893 - Handle unknown format when no permission

app/controllers/concerns/hyc/download_analytics_behavior.rb, spec/controllers/hyrax/downloads_controller_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1904
=> HYC 1904 - Tracking Work-ID in Download Analytics Behavior

config/authorities/biomed_departments.yml, config/authorities/departments.yml, config/authorities/masters_papers_depts.yml, config/authorities/proquest_departments.yml, spec/fixtures/authorities/proquest_departments.yml
https://unclibrary.atlassian.net/browse/HYC-1903
https://unclibrary.atlassian.net/browse/HYC-1908
* Changed `Public Health Leadership Program` to `Department of Public Health Leadership and Practice` in the existing department vocabulary
* Deactivated MPH@UNC in masters paper dept yaml to remove the entry from the dropdown for adding masters papers
=> HYC-1903 -Update Department Name for PHLP

app/views/shared/_footer.html.erb
https://unclibrary.atlassian.net/browse/HYC-1924
=> Update link to match new library site

Gemfile, Gemfile.lock, app/overrides/lib/rdf/model/uri_override.rb
https://unclibrary.atlassian.net/browse/HYC-1941
* Pull in patch release branch of ruby rdf which may resolve FrozenErrors
=> HYC-1941 - RDF FrozenError

app/controllers/accounts_controller.rb, spec/controllers/accounts_controller_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1918
Add test to verify that creating accounts is case insensitive, and update the accounts controller
=> HYC-1918 - Ensure accounts are lowercase

app/controllers/concerns/hyc/download_analytics_behavior.rb, spec/controllers/hyrax/downloads_controller_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1954
* If no work record is found, then return Unknown for work type
=> HYC-1954 - Handle unknown work type in download event

app/services/tasks/dimensions_ingest_service.rb, spec/services/tasks/dimensions_ingest_service_spec.rb
Part of https://unclibrary.atlassian.net/browse/HYC-1957
=> HYC-1950 Remove File Delete in Dimensions Ingest (Follow Up)

Gemfile.lock
https://unclibrary.atlassian.net/browse/HYC-1953
* Updating commit ref after merging hyrax PR: https://github.com/UNC-Libraries/hyrax/pull/11
=> HYC-1953 - Admins cannot override file visibility settings on edit file page

app/controllers/catalog_controller.rb
https://unclibrary.atlassian.net/browse/HYC-1965
=> HYC-1965 - Include identifier field in default search fields

lib/tasks/dissertations_page_count.rake
* Add utility to count page numbers for dissertations within hyc
=> HYC-1974 Total Dissertation Page Count

app/overrides/controllers/concerns/hyrax/works_controller_behavior_override.rb, spec/controllers/concerns/hyrax/works_controller_behavior_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1998
* Check if an embargo is added during update of a work, and return that permissions have changed if so
=> HYC-1998 - Trigger permission prompt for added embargos

app/overrides/lib/active-fedora/rdf/indexing_service_override.rb, spec/lib/active_fedora/rdf/indexing_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-1968
* Add test to demonstrate joint department failure since the mapping has multiple terms, and address the issue
=> HYC-1968 - Indexing of affiliations with multiple terms

app/helpers/hyc_helper.rb, spec/helpers/hyc_helper_spec.rb
https://unclibrary.atlassian.net/browse/HYC-2047
Prevent error when depts are select in the advanced search, which produces a list of dept keys
=> HYC-2047 - Prevent error when depts are select in the advanced search

config/authorities/departments.yml, spec/lib/active_fedora/rdf/indexing_service_spec.rb, spec/renderers/hyrax/renderers/person_attribute_renderer_spec.rb, spec/services/departments_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-2052
Update vocabulary to fix validation errors. Add validation test to detect when there are issues
=> HYC-2052 - Fix department vocab issues

app/controllers/bot_detect_controller.rb, public/robots.txt, spec/controllers/bot_detect_production_spec.rb
* Removes googlebot robots.txt exception
* Adds challenge for paging
=> No google exception

Gemfile, Gemfile.lock, config/routes.rb, solr/config/solrconfig.xml
https://unclibrary.atlassian.net/browse/HYC-2064
Depends on https://gitlab.lib.unc.edu/cdr/hyc-gems/-/merge_requests/121
Note: This requires a full re-index
=> Set up dynamic sitemap

app/services/cdr_license_service.rb, app/services/cdr_rights_statements_service.rb, app/views/records/edit_fields/_rights_statement.html.erb, spec/services/cdr_license_service_spec.rb, spec/services/cdr_rights_statements_service_spec.rb
https://unclibrary.atlassian.net/browse/HYC-2006
=> HYC-2006 - Allow admins to see all rights statements on all forms

app/controllers/concerns/hyc/download_analytics_behavior.rb
https://unclibrary.atlassian.net/browse/HYC-2119
=> HYC-2119 - Return early for empty work data

app/overrides/controllers/concerns/hyrax/works_controller_behavior_override.rb, app/presenters/hyrax/shared_delegates.rb, config/initializers/mime_types.rb, spec/controllers/concerns/hyrax/works_controller_behavior_spec.rb
https://unclibrary.atlassian.net/browse/HYC-2087
=> HYC-2087 - Make dc_xml and xml extensions work

app/views/hyrax/my/works/_facet_limit.html.erb
https://unclibrary.atlassian.net/browse/HYC-2090
=> [HYC-2090] Works Dashboard Dropdown Bug Fix
